### ISSUE TITLE
C signed and unsigned comparison

### ISSUE THREAD

**Issue by Drevanoorschot** [utwente-fmt/vercors#1028]
While exploring how to deal with signed unsigned integers in LLVM, I was curious to what extend signed and unsigned integers are supported by the C verifier. I came up with the following example that is verified incorrectly:
```c
//@ ensures \result == 1;
int test() {
    unsigned int x = 1;
    int y = 0;
    return (x - 2) > y ? 1 : 0;
}

int main() {
    printf("test(): %s\n", test() ? "true" : "false");
}
```

Compiling and running this example with both gcc and clang yields `test(): true` implying the ensures clause would hold for the the function `test()`. However, when verifying the program (omitting the main method), it yields the following verification error:
```======================================
 At examples/private/signed_unsigned.c:2:
--------------------------------------
    1  
      [---------------------------
    2  //@ ensures \result == 1;
    3  int test() {
    4      unsigned int x = 1;
    5      int y = 0;
    6      return (x - 2) > y ? 1 : 0;
    7  }
       ---]
    8  //
    9  //int main() {
--------------------------------------
 Interpreted at /tmp/vercors-interpreted-10917141066458857538.i:9:3 as:
--------------------------------------
    7  # 1 "<stdin>" 2
    8  
        [-------------------------
    9  //@ ensures \result == 1;
   10  int test() {
   11      unsigned int x = 1;
   12      int y = 0;
   13      return (x - 2) > y ? 1 : 0;
   14  }
       -]
   15  //
   16  //int main() {
--------------------------------------
[1/2] Postcondition may not hold, since ...
--------------------------------------
 At examples/private/signed_unsigned.c:2:
--------------------------------------
    1  
      [---------------------------
    2  //@ ensures \result == 1;
       ---------------------------]
    3  int test() {
    4      unsigned int x = 1;
--------------------------------------
 Interpreted at /tmp/vercors-interpreted-10917141066458857538.i:9:13 as:
--------------------------------------
    7  # 1 "<stdin>" 2
    8  
                  [------------
    9  //@ ensures \result == 1;
                   ------------]
   10  int test() {
   11      unsigned int x = 1;
--------------------------------------
[2/2] ... this expression may be false (https://utwente.nl/vercors#postFailed:false)
======================================
```

Mixing signed and unsigned integers is of course asking for trouble, but i was wondering to what extend this behaviour is/should be supported by VerCors. I.e. is signed and unsigned typing a responsibility of the programmer/compiler or the verifier?

**Comment by niomaster** [comment]
This is rooted in our lack of support for finite numeric types. For integral types (`{signed|unsigned} {int|long|long long}` etc.) we pretend they are unbounded integers, and for floating types (`float`, `double`) we pretend they are rationals with infinite precision. This can be useful to show that your algorithm also works in the unbounded case, and this additionally usually makes proofs easier. In this case the infinite notion of types is more general, and hence the proof does not go through. There are of course cases in which the finite version is not sensible even if the infinite proof goes through.

We do want to support bounded types, a precondition for that is resolving [this discussion](https://github.com/utwente-fmt/vercors/discussions/1018). In essence we would have modes that precisely model numeric operations at the bit level (expensive proofs), and a mode that bans overflow from occurring (easier proofs but far less general).

**Comment by bobismijnnaam** [comment]
> Mixing signed and unsigned integers is of course asking for trouble

Just to be annoying, pedantic and complete, in case anyone ever gets to implementing this: the c11 spec draft (https://www.open-std.org/jtc1/sc22/wg14/www/docs/n1570.pdf) mentions in 6.5.9:

> If both of the operands have arithmetic type, the usual arithmetic conversions are performed. Values of complex types are equal if and only if both their real parts are equal and also their imaginary parts are equal. Any two values of arithmetic types from different type domains are equal if and only if the results of their conversions to the (complex) result type determined by the usual arithmetic conversions are equal.

"the usual arithmetic conversions" define behaviour of signedness vs. unsignedness in 6.3.1.8. Future work for now :p
