### ISSUE TITLE
Adding support for structs in C backend

### ISSUE THREAD

**Issue by sakehl** [utwente-fmt/vercors#1055]
Hi,

I'm trying to add support for structs. See this branch: [sakehl/vercors/tree/better-c-support](https://github.com/sakehl/vercors/tree/better-c-support).

Anyway, I'm now thinking of a suitable encoding for the Viper back end, and could not come to a feasible solution. Let's have a discussion here.

This is the example C program I'm trying to translate.
```c
#include <assert.h>

struct MyStruct {
    int x;
    int y;
};

void doSomething(struct MyStruct s) {
    s.x = 0;
    s.y = 0;
}

int main() {
    struct MyStruct s;
    // assert(s.x == 10); // Should fail
    s.x = 10;
    s.y = 20;

    assert(s.x == 10);
    doSomething(s);
    assert(s.x == 10);

    return 0;
}
```

### Option 1: Treat it similarly as the [tuple ADT](https://vercors.ewi.utwente.nl/wiki/#axiomatic-data-types)
Would turn into (PVL code)
```java
adt MyStruct {
  pure MyStruct cons(int x, int y);
  pure int get_x(MyStruct s);
  pure int get_y(MyStruct s);

  axiom (\forall int x, int y; {:get_x(cons(x, y)):} == x);
  axiom (\forall int x, int y; {:get_y(cons(x, y)):} == y);
  axiom (\forall int x1, int x2, int y1, int y2; 
    (cons(x1, y1) == cons(x2, y2)) ==> (x1 == x2 && y1 == y2));
}

pure MyStruct set_x(MyStruct s, int x) {
  return MyStruct.cons(x, MyStruct.get_y(s));
}

pure MyStruct set_y(MyStruct s, int y) {
  return MyStruct.cons(MyStruct.get_x(s), y);
}

void doSomething(MyStruct s) {
    s = set_x(s, 0);
    s = set_y(s, 0);
}

int main() {

    MyStruct s;
    // assert(MyStruct.get_x(s) == 10); // Fails

    s = set_x(s, 10); // s.x = 10;
    s = set_y(s, 20); // s.y = 20;

    assert(MyStruct.get_x(s) == 10); // assert(s.x == 10);

    doSomething(s);
    // Struct is passed as copy, so changing it inside a function does not matter.  
    assert(MyStruct.get_x(s) == 10); // assert(s.x == 10);
   return 0;
}
```
##### Comments:

* We could never set different fields in a parallel block, e.g. this would not work
  ```java
  par threads (int tid = 0 .. 2) {
    if(tid == 0){
        s = set_x(s, tid); // s.x = tid
    } else {
        s = set_y(s, tid); // s.y = tid
    }
  }
  ```
  Although I just noticed that this is never allowed since 'declarations outside this node must not be altered'. 
* We need to replace all `s.x = ...` by something like `s = set_x(s, ...)`. Not per se hard, but less natural.
* It seems that ADTs are mostly immutable, whilst a structure is typically mutable. Thus the correspondence seems off. 

### Option 2: Treat it like a class
```java
class MyStruct {
  int x;
  int y;
}

int main() {

  MyStruct s;
  s = new MyStruct();
  // assert(s.x == 10); // Fails

  s.x = 10;
  s.y = 20;

  assert(s.x == 10);
  doSomething(s);
  assert(s.x == 10);

  return 0;
}

  context Perm(s.x, read);
  context Perm(s.y, read);
void doSomething(MyStruct s) {
    MyStruct s_copy = new MyStruct();
    s_copy.x = s.x;
    s_copy.y = s.y;
    
    s_copy.x = 0;
    s_copy.y = 0;
}
```
##### Comments:
* We need to give permission to the fields now if one wants to use them. (see `doSomething`).
* And when passed as a parameter, we need to first do a copy, since structs are passed by value, not by reference.

## Additional thoughts
The first option seems best I think, since it stays more true to the 'pass by value' nature of structs and no additional permissions annotations are needed. Although why I'm hesitating because it does not seem possible to update parts of a struct in different threads.

## Pointers
A different thing is that I also wanted to do something like:
```c
void doSomething2(struct MyStruct * s) {
    s->x = 0;
    s->y = 0;
}

int main(){
  struct MyStruct s;
  doSomething2(&s);
  assert(s.x == 0 && s.y == 0);
}
```
Where I get `[ERROR] Non-trivial instances of the address-of operator are not supported.`.

Which I get, since here we make from a 'normal' variable which normally is passed by value, instead of something that can be passed by reference. So suddenly, permissions need to be added to prove things.

Is this something we want to support in VerCors? Since they are used sometimes in the programs I'm using, but it seems hard to do this in a good way, from a quick glance.

**Comment by pieter-bos** [comment]
Hey! This is actually on my medium-term to implement list :). We've also discussed it before fairly extensively - what it comes down to is that a first solution must support:

- Addressing the struct as a whole, so you can have a `struct Point3D *p` and `Perm(p, write)`
- Addressing the components of a struct, so you can have `p->x` and `Perm(p->x, write)`

I think that non-trivial cases of `&` are closely related enough that we might as well implement them in the same changeset. Some considerations:

- `&p->x` is an `int *`, so it has to act uniformly with any other int pointer. I see no way to do this other than treat every int location as a `Ref` and have one field for all int pointers.
- Any struct whose contents are defined thus just has to be a `Ref`. I think a definition similar to just an n-tuple of `Ref`s is fine, but we can also axiomatize that structs cannot overlap (in the VerCors fragment of C, anyway)
- I don´t know yet how to deal with `Perm(p, write)`. When we discussed we decided we should just inline all the permissions (so e.g. desugar `Perm(p, write)` to `Perm(&p->x, write) ** Perm(&p->y, write) ** Perm(&p->z, write)`), but I think a pretty common API design is to leave structs intransparent in header definitions when you pass them to a library, so there needs to be some abstraction. I know that prusti does this kind of thing just via predicates (so you can leave the predicate abstract when on the usage side), but I think there was some problem with it for C.
- This supports `&` for locations in composite types, left is primitive locals: those we can lift to `Ref`s similarly, again just with the same type-determined field. The encoding then is to exhale write permission to them on method exit (maybe it has to be in a try-finally, not sure).

Finally I want to mention that we considered earlier to detect situations in which a struct just behaves like a class and support that, but at this point I no longer think it would be very useful - but maybe you disagree for your cases.

**Comment by sakehl** [comment]
Thanks for the reply. Considering your reply, I see that you kinda need permission to all fields, so that makes sense.

For now, I've added 'simple' support for structs by considering them as classes, and doing two extra things:
* When it is passed as an argument, it is first copied.
* When a struct is assigned to another struct, (e.g. `s == *s0` below), it is copied by value, not by reference.

With these, I get the following file to verify. It also runs correctly when passed to the GCC compiler. 
(see changes untill https://github.com/utwente-fmt/vercors/commit/2d408a9b8481b38c3941fa2e743e03756dcf9c4e)
```c
#include <assert.h>
#include <stdlib.h>

struct MyStruct {
    int x;
    int y;
};

/*@
 context Perm(s.x, write);
 context Perm(s.y, write);
@*/
void doSomething(struct MyStruct s) {
    s.x = 0;
    s.y = 0;
}

/*@
  requires s != NULL;
  context Perm(s, write);
  context Perm(s->x, write);
  context Perm(s->y, write);
  ensures s->x == 0 && s->y == 0;
@*/
void doSomething2(struct MyStruct * s) {
    s->x = 0;
    s->y = 0;
}

/*@
  ensures \result != NULL;
  ensures Perm(\result, write);
  ensures Perm(\result->x, write);
  ensures Perm(\result->y, write);
  ensures \result->x == x;
  ensures \result->y == y;
@*/
struct MyStruct* cons(int x, int y)
// {
//     struct MyStruct *s = malloc(sizeof(struct MyStruct));
//     s->x = x;
//     s->y = y;
//     return s;
// }
;

int main() {
    
    struct MyStruct *s0 = cons(10, 20);
    struct MyStruct s;
    // Should fail
    // assert(s.x == 10); 
    s = *s0;

    assert(s.x == 10);
    doSomething(s);
    assert(s.x == 10);
    doSomething2(s0);
    assert(s0->x == 0);
    assert(s.x == 10);

    #pragma omp parallel for
    for(int i = 0; i < 2; i++)
    /*@
        requires i == 0  || i == 1;
        context i == 0 ==> Perm(s.x, write);
        context i == 1 ==> Perm(s.y, write);
        ensures i == 0 ==> s.x == 0;
        ensures i == 1 ==> s.y == 1;
    @*/
    {
        if(i == 0) {
            s.x = i;
        } else {
            s.y = i;
        }
    }

    assert(s.x == 0 && s.y == 1);
    return 0;
}
```


For a more _struct_ured approach, probably the above things you are saying makes a lot of sense. The type-checking things I added can be the same, but then we need to alter more things in the `LangCtoCol` file and probably add actually structs to the internal AST of COL.
