### ISSUE TITLE
How to treat pointers & arrays in C backend

### ISSUE THREAD

**Issue by sakehl** [utwente-fmt/vercors#1056]
As currently is the case in VerCors, array syntax like
```c
int a[];
```
is equivalent to declaring a pointer.
```c
int *a;
```

Now apparently there is a slight difference between them, but indexing a pointer should work the same as indexing a pointer (see https://c-faq.com/aryptr/aryptrequiv.html). And an array can be _decayed_ towards a pointer.

Anyway, I've made some changes, since I wanted to support the syntax
```c
int a[5];
```

And changed C arrays to the `TArray` type, so the `EncodeArrayValues` picks it up.

But now the decaying of an array towards a pointer does not work anymore.

So I was thinking of good solutions.

#### Option 1: No difference between pointers and arrays
So everything just becomes pointers. I'd need to come up with something like `NewPointerArray(Type t, int size)` and we encode `a[5]` like this.

Since pointers and arrays are only different in three aspects (what the c-faq seems to say), it should not matter to much?
I.e. 
> The exceptions are when the array is the operand of a sizeof or & operator, or is a string literal initializer for a character array. [[footnote]](https://c-faq.com/aryptr/stringw.html) See questions [6.23](https://c-faq.com/aryptr/arraynels.html), [6.12](https://c-faq.com/aryptr/aryvsadr.html), and [1.32](https://c-faq.com/decl/strlitinit.html), respectively.

#### Option 2: Make something that decays things
So the type checker accepts arrays when pointers are okay. And eventually, in the back-end to Silver, we write a conversion function from arrays to pointers when needed.

- Seems probably too complicated for the corner cases.

Any thoughts?

**Comment by pieter-bos** [comment]
Yeah we mostly just decay arrays into pointers currently, the aspect in which they are meaningfully different for us (and for this we've left room in the current abstraction to do some encoding here) is that an array of array of T is not the same as a pointer to array of T. I think a nested array type has some restrictions, I believe at least a constant size, but I'm not too sure at the moment. In any case there needs to be some notion that `int x[3][3];` means that `x[1]` is not a value (?), `x[0][8]` is well-defined (?), permission to `x[1]` does not make sense, etc. (Some of these might not be true, can't check right now).

**Comment by pieter-bos** [comment]
From an engineering perspective I'm pretty sure that pointer decay is a typing rule for the C-flavoured array type? Should be some mention of it in `getCoercion` I believe.
