### ISSUE TITLE
Local variables can be used before their declaration

### ISSUE THREAD

**Issue by Ellen-Wittingen** [utwente-fmt/vercors#1109]
For C, C++, Java, and PVL, local variables can be used before their declaration. For instance, writing the following in C verifies successfully:
```
void test() {
    a = 5;
    int a = 10;
}
```
However, when running a C compiler (clang) on this example, it throws an error that `a` on line 2 is undeclared. The C++ compiler (clang++) throws an error as well, but I did not test it for Java.

If compilers throw an error on this pattern, should VerCors not do the same?
Or was a deliberate choice made to allow the pattern?

**Comment by pieter-bos** [comment]
Well spotted! Generally we presume that the example compiles before it is passed into VerCors, specifically to avoid spending a lot of time re-implementing all checks a compiler already does within VerCors. We nevertheless reject nonsense anyway (like naming variables that don't exist), but really only when it is convenient to us. I think we should probably eventually revisit this stance, but for now this is working as intended.
