### ISSUE TITLE
Cannot read-scale a predicate

### ISSUE THREAD

**Issue by bobismijnnaam** [utwente-fmt/vercors#1128]
The following program:

```
resource p();

requires [read]p();
void m();
```

Gives the output:

```
[INFO] Starting verification
======================================
At test.pvl
--------------------------------------
    1  resource p();
    2  
                [----
    3  requires [read]p();
                 ----]
    4  void m();
    5
--------------------------------------
You cannot have a wildcard outside of a permission statement.
======================================
```

I think this is because PredicateApply is not lifted into a location in the DisambiguateLocations phase, so the ReadToValue phase doesn't pick it up. Not sure what PredicateApply should be lifted into, though, maybe also a Perm like they do in Viper?

**Comment by pieter-bos** [comment]
You can write `Perm(p(), read)` or `Value(p())` (I tend to prefer the latter now). We haven't decided what scaling by `read` should mean in general: <https://github.com/utwente-fmt/vercors/discussions/891>

**Comment by bobismijnnaam** [comment]
Ah, I didn't know that we support that, then I don't need scaling, thanks :pray:
