### ISSUE TITLE
Parallel Block encoder, saving ranges as variables

### ISSUE THREAD

**Issue by sakehl** [utwente-fmt/vercors#1165]
So in the parallel block encoding ParBlockEncoder:

https://github.com/utwente-fmt/vercors/blob/72735981dd3ab612f93aa918d6b152f80dee9d7e/src/rewrite/vct/rewrite/ParBlockEncoder.scala#L260-L265

I've added this code such that if something like
```
void main(int N){
  par(tid=0..N)
    requires E1
    ensures E2
 {
    ...
  }
}
```
will be rewritten such that rangeValue for high, is just saved as `N` (_wanted case_) instead of `hi_tid=N`. (_fallback case_)

This is important, since E1 and E2 get automatically quantified over the range of tid.

In the case we have just saved N, we get:
`(forall int tid=0..N; E1);`
instead of
`(forall int tid=0..hi_tid; E1);`

And because we have no access hi_tid, and cannot add annotation about hi_tid.

And if we ever want to rewrite quantifiers or reason about things, this becomes hard/impossible. This is especially essential for any GPU kernels, since they each have 6 parallel blocks (3 thread-blocks and 3 local-threads).

Anyway, the approach now, is working, but is brittle. Since it is a a conservative safe analysis, but if it comes across a node it does not know, it goes to the fallback case. 

I was thinking, we could also analyse any referred variables.

If the variable referenced is of primitive type or an ADT type, and the variable is local/a parameter, it cannot be altered in a parallel block.
(This is correct right?)

If we can conclude this, we can end up in the _wanted_ case.

I posted this here, mainly to see if this is a correct assumption or if you might have other ideas. Especially @pieter-bos if you have an opinion on this.

If you think this would work, I'll implement this.

**Comment by pieter-bos** [comment]
I'm struggling to understand a bit under what circumstances you need to explicitly reason about the upper bound (i.e. `hi_tid`) - it's a constant with respect to the parallel block so you should have local inference about its value. In the case that the bound value is heap-dependent you may have problems if you are also using `--no-infer-heap-context-into-frame`. Or maybe you are talking about your rewriting analysis, but there it should be fairly trivial to just internalize that `hi_tid == N`, or?

Anyway, I don't have strong objections to do something like this, but please be careful about well-formedness constraints. Even when you can ascertain that an evaluation would not change, it's possible we can't conclude from the local thread contract that the expression is still well-formed (think division by zero, sequence subscript, that sort of thing).
