### ISSUE TITLE
Implement and merge VCLLVM

### ISSUE THREAD

**Issue by alexchandel** [utwente-fmt/vercors#1191]
[There is a research project that prototyped an extension of VerCors to LLVM IR](https://link.springer.com/chapter/10.1007/978-3-031-57259-3_15).  This would be very useful, as it might enable some level of verification for any language that compiles on LLVM.  Can any of this be adopted and merged into VerCors?

**Comment by pieter-bos** [comment]
Hi, thanks for your interest! This tool is nominally merged already, the source is [here](https://github.com/utwente-fmt/vercors/tree/dev/src/llvm), but it's still fairly experimental, and currently Linux-only. There's two PhD candidates working on improving the support we currently have. As you sketch a main goal is indeed to enable some kind of static verification support for some/all llvm-based languages.

If you'd like to try it out VerCors accepts a `.ll` file as of v2.1+. There's no examples/documentation I can point you to yet, as we're still figuring out the specification language and whatnot, but here's an example that was written in the context of the paper and should work:

```llvm
!VC.global = !{!0}
!0 = !{
!"pure i32 @fib(i32 %n) =
	br(icmp(sgt, %n, 2),
		add(call @fib(sub(%n, 1)), call @fib(sub(%n, 2))),
		1);"
}
define dso_local i32 @fibonacci(i32 noundef %0)
!VC.contract !{
!"requires icmp(sge, %0, 1);",
!"ensures icmp(eq, \result, call @fib(%0));"
}
{
	%2 = icmp sgt i32 %0, 2
	br i1 %2, label %3, label %9
  3:
	%4 = sub nsw i32 %0, 1
	%5 = call i32 @fibonacci(i32 noundef %4)
	%6 = sub nsw i32 %0, 2
	%7 = call i32 @fibonacci(i32 noundef %6)
	%8 = add nsw i32 %5, %7
	br label %10
  9:
	br label %10
  10:
	%.0 = phi i32 [ %8, %3 ], [ 1, %9 ]
	ret i32 %.0
}
```

Feel free to reach out if you have further questions.
