### ISSUE TITLE
Java.lang exception

### ISSUE THREAD

**Issue by DanTUe** [utwente-fmt/vercors#127]
The following PVL program gives a Java Stack trace exception in VerCors:

```
class Point {
}

class X {
  Point p;
  
  requires Perm(this.p,33);
  void run() {
  }
}
```

I run this with:
``
./unix/bin/vct --silver=silicon examples/dan/update-point.pvl
``

**Comment by wytseoortwijn** [comment]
See also the discussion at #126.

**Comment by sjcjoosten** [comment]
We like the Java defaults, so the correct behavior would be to initialise p with null.

**Comment by sjcjoosten** [comment]
I'm closing this issue because it seems indeed fixed
