### ISSUE TITLE
--explicit flag

### ISSUE THREAD

**Issue by sjcjoosten** [utwente-fmt/vercors#128]
The verification of:
```
./unix/bin/vct --silicon --explicit ./examples/manual/functions.pvl
```
does not work with the ``explicit`` flag, but the error message is too cryptic

**Comment by sjcjoosten** [comment]
This seems to be an issue with the viper printer. If I write:

```
./unix/bin/vct --silicon ./examples/manual/functions.pvl
```

it simply works, adding the ` --explicit` flag causes a Java exception that should be fixed (probably by generating a unique name somewhere). Here is a minimal example for reproducing this behavior:

```
class counter {
  resource state()=true;
  
  requires state();
  boolean get()=unfolding state() in true;
}
```

**Comment by niomaster** [comment]
The vercors source mentions that explicit exists, because chalice cannot represent predicates with arbitrary arguments. Since we no longer want to support that backend (and silicon can represent predicates with arbitrary arguments), I nominate we remove the functionality altogether.
