### ISSUE TITLE
  CallPreCondition:AssertionFalse

### ISSUE THREAD

**Issue by DanTUe** [utwente-fmt/vercors#129]
I tired to verify the following PVL program in VerCors:
```
class ReentLock {
    requires true;
    ensures true;
    void re_lock() {
    }
}
class Statement {
    void lockV(ReentLock y) {
     y.re_lock();	
	}
}
```
The error indicates the precondition of method y.re_lock() does not hold. However its precondition is specified as true.

**Comment by wytseoortwijn** [comment]
Don't forget `null` checks: `y` might actually be `null`, in which case the precondition can not be checked (perhaps the error message can be somewhat improved here). The following program verifies:

```java
// ./unix/bin/vct --silicon ./examples/graphs/test1.pvl

class ReentLock {
    requires true;
    ensures true;
    void re_lock() {
    }
}
class Statement {
  requires y != null;
  void lockV(ReentLock y) {
    y.re_lock();	
  }
}
```

**Comment by DanTUe** [comment]
Thanks! It would be nice if the error message in this case could be clearer.
