### ISSUE TITLE
Looking for example where VerCors says 'Fail' without error

### ISSUE THREAD

**Issue by sjcjoosten** [utwente-fmt/vercors#130]
Previously, we encountered an example in which VerCors in which the final verdict was FAIL, but there was no error given. The diagnosed problem was that Viper had failed on the program and given a proper error, but the error wasn't recognised (or expected) by VerCors. In such cases, we would like to see

1. a proper error message
2. as a backup, the raw Viper message

I can't seem to find a script for which this issue occurs anymore: we probably keep implementing solution 1 for the cases in which they occur. However, as these issues keep popping up, I want to make an issue that builds solution 2 (as a fallback), so I am looking for a VerCors bug that has not been fixed through solution 1 yet. Does anyone know how to make Viper give an unexpected error?

**Comment by wytseoortwijn** [comment]
The following PVL snippet gives a failure without further clarification. (This is probably not a minimal example.)

```java
class Node {
	int val;
	seq<Node> next;
	
	resource State() =
		Perm(this.val, write) ** Perm(this.next, write);
}

class Test {
	
	requires (\forall Node n; n in G; n != null);
	requires (\forall* Node n; n in G; n.State());
	requires (\forall Node n; n in G; n.next.length > 0);
	void test(set<Node> G) {
	}
}

```

**Comment by wytseoortwijn** [comment]
*the problem is in the third requires clause; changing it to `requires (\forall Node n; n in G; unfolding n.State() in n.next.length > 0);` would solve the problem.

**Comment by niomaster** [comment]
It's now very hard to get vercors to not output anything.
