### ISSUE TITLE
--version flag

### ISSUE THREAD

**Issue by wytseoortwijn** [utwente-fmt/vercors#165]
VerCors should have a `--version` flag that gives information on which version of VerCors is installed.

**Comment by sjcjoosten** [comment]
In the Ampersand project, we set up the version with a number set in the code (which we bump) plus a short hash of the latest git checkout version, plus the pound character `#` if the last compilation was done on a version that had local changes. All of this is extremely useful for getting a good answer when asking 'what version are you on': the version number in the code tells us how far behind someone is, and the hash tells us whether or not their version is the exact same as the latest version.

**Comment by niomaster** [comment]
We have a `--version` flag now, but I do agree with all sebastiaans ideas, which we do not have. I think we should investigate what the easiest option is to integrate with SBT. I believe the colloquial term for differing from a release version is `x.y.z-SNAPSHOT`.

**Comment by sjcjoosten** [comment]
Thanks for the compliment, and for implementing the version flag! The colloquial term for differing from a release version indeed is snapshot (it helps to know the hash as well), the colloquial term for differing from a versioned version is 'dirty'.

**Comment by niomaster** [comment]
@bobismijnnaam Is this done via the git hash snippet in build.sbt?

**Comment by bobismijnnaam** [comment]
Yes, in build.sbt and Main.java. On master only the version is printed and on any other branch the commit is included as well. If there are changes, "with changes" is appended, so not # or `SNAPSHOT`. This is easy to change though.

**Comment by niomaster** [comment]
I think that's more than enough for now!
