### ISSUE TITLE
Travis regression

### ISSUE THREAD

**Issue by sjcjoosten** [utwente-fmt/vercors#167]
We've been accepting some errors from Travis, but recently things seem to have gotten worse: https://travis-ci.org/utwente-fmt/vercors/builds/512500857
It would be good if we could get the set of failing tests back to only those that are non-deterministicly failing. If you find tests that cannot be fixed quickly, feel free to disable and make a separate issue to re-enable the (fixed) test.

**Comment by niomaster** [comment]
I get the same set of failures locally compared to the linked travis build, so I guess they are all deterministic :)

A bunch of the errors are just because C would no longer be supported after merging #156, so the C tests give unexpected results. I have grouped the other errors in separate issues.

**Comment by niomaster** [comment]
Since the issues are split out we could close this issue, however the master branch fails due to a different error not yet investigated:

https://travis-ci.org/utwente-fmt/vercors/builds/512474272?utm_source=github_status&utm_medium=notification

**Comment by sjcjoosten** [comment]
All failing tests are deterministic again, that's great! Let's get travis to work again then!

**Comment by niomaster** [comment]
Re: the master branch failing, that was due to some repository being down temporarily, so the master branch passes again.
