### ISSUE TITLE
Broken link in readme

### ISSUE THREAD

**Issue by sjcjoosten** [utwente-fmt/vercors#176]
Looking at the readme at https://github.com/utwente-fmt/vercors/#building
I am provided with a link to the vercors/viper pages, but the link points to a page that does not exist. Furthermore, the page http://utwente-fmt.github.io/vercors/TryOnline.html#install does not mention symbolic links (this page can be edited in the docs directory of this repo)

**Comment by sjcjoosten** [comment]
@HenkMulder or @niomaster , if this would be easy to fix for one of you, then let me know by assigning yourself?

**Comment by HenkMulder** [comment]
I already made a pr with a commit that should fix the link. I've also added the hint that Unix users can use the travis_build.sh script to automatically create the symbolic links and build the project.
I didn't know about the other IO pages. I think work from @niomaster for issue #166 will change the other instructions on building VerCors anyway. Therefore I am not going to update those pages now.

**Comment by sjcjoosten** [comment]
Thank you Henk, that fixes this issue then!
