### ISSUE TITLE
Trivial assert doesn't prove for yield variable

### ISSUE THREAD

**Issue by sjcjoosten** [utwente-fmt/vercors#179]
Marieke and I encountered a bug during VerifyThis, thanks to Marieke for isolating it.
The following `pvl` code does not prove (would be better if it did):

```
class Ref {

      yields int[] a;
      ensures a != null;
      void m() {
          int[] a = new int[4];
      }
}
```

**Comment by niomaster** [comment]
The cause seems to be that yield statements are not considered when renaming variables, specifically in the flatten pass. `a` is renamed to `a__1` within the method, but `a` is not renamed in the ensures statement.

**Comment by sjcjoosten** [comment]
Thanks for the diagnosis!

**Comment by niomaster** [comment]
From the examples it seems that the yields statement works as a declaration statement, is that intended? e.g. this verifies:

```
class Ref {
      yields int[] a;
      ensures a != null;
      void m() {
          a = new int[4];
      }
}
```

In that case the first example is not really supposed to verify, as `a` is redeclared within a deeper scope, and the outer `a` is not assigned.

**Comment by sjcjoosten** [comment]
Ah you're perfectly right, thanks!

Can you improve the error message or ensure that second declarations done this way are simply forbidden? I seem to recall that we also forbid the following in pvl (didn't test yet though):

```
int x = 3;
int x = 3;
```

**Comment by niomaster** [comment]
The above is indeed forbidden by the ReorderAssignments pass.

The problem generalizes to all arguments, e.g. this verifies:

```
class DuplicateName {
    void test(int abc) {
        int abc;
    }
}
```
