### ISSUE TITLE
Cannot access members on objects within sequence

### ISSUE THREAD

**Issue by bobismijnnaam** [utwente-fmt/vercors#190]
The following code snippet yields that I cannot access the field `even` when it is within a sequence, where I would expect such access to be allowed.

```
class Node {
  boolean even;
}

class MyClass {
  seq<Node> ns;

  void foo() {
    if (ns[0].even) {}
  }
}
```

Error:

```
Plain foo
Parsed 1 file(s) in: 191ms
Comparing Boolean with false as Boolean
At file pseudo-issue.pvl from line 9 column 9 until line 9 column 18: even is not a pseudo field of (Cell<Node>).
Triggered by file pseudo-issue.pvl from line 9 column 9 until line 9 column 18:
The final verdict is Error
entire run took 257 ms
```

**Comment by wytseoortwijn** [comment]
This is a general problem of the indexing notation: accessing fields (`a[i].f`) or calling methods/functions (`a[i].m()`) from arrays/sequences (`a`) gives a type checking error (I think).

**Comment by bobismijnnaam** [comment]
I also tried `ns[0].item.even` (because that's what it seems to be looking for if you look in vercor's source) but I think then I got a permission error. Not sure though.

**Comment by sjcjoosten** [comment]
I'm even getting this on a[i].length, which is definitely a regression (i.e. I'm pretty sure it worked at some point)
