### ISSUE TITLE
Perm in pure functions

### ISSUE THREAD

**Issue by bobismijnnaam** [utwente-fmt/vercors#193]
I would like the following to work:

```
class MyClass {
  pure boolean hasPerm(int[] arr) = Perm(arr, 1/2);

  int[] P;

  requires hasPerm(P);
  void foo() {
    assert Perm(P, 1/2);
  }
}
```

Vercors gives me the following error:

```
Pure hasPerm
Plain foo
Parsed 1 file(s) in: 187ms
At file heap-location-issue.pvl from line 2 column 37 until line 2 column 50: first argument is not a heap location
Triggered by file heap-location-issue.pvl from line 2 column 37 until line 2 column 50:
The final verdict is Error
entire run took 243 ms
```

As far as I can tell an `int[]` can only be allocated on the heap, so inside hasPerm vercors should be able to tell that `arr` is indeed a heap location. However, the semantics of pvl are not entirely clear to me, so maybe I'm missing something.

**Comment by wytseoortwijn** [comment]
There are several problems with this code snippet, the first being that `Perm(arr, 1/2)` is of type `resource`, rather than `boolean`. So in terms of typing, you might want something like:

```java
resource hasPerm(int[] arr) = Perm(arr, 1/2);
```

However, this is not correct either, since `arr` is call-by-value (the actual contents of `arr` is shared memory, but the variable `arr` is itself local).

You probably want something like:

```java
class MyClass {
  resource hasPerm(MyClass c) = c != null ** Perm(c.P, 1/2);

  int[] P;
	
  MyClass() {
  }
  
  requires hasPerm(this);
  void foo() {
    unfold hasPerm(this);
    assert Perm(P, 1/2);
  }
}
```

**Comment by bobismijnnaam** [comment]
Aha, interesting. I got as far as this:

```
class MyClass2 {
  int[] P;

  pure resource hasPerm() = Perm(P, 1/2);

  requires hasPerm();
  void foo() {
    assert Perm(P, 1/2);
  }
}
```

But the assert was still not verified. With unfold I'll probably get there, thanks.

**Comment by wytseoortwijn** [comment]
So the error message _"first argument is not a heap location"_ that VerCors gives applies to the `Perm(arr, 1/2)` part of the code snippet: `arr` is indeed not a heap location. Perhaps the error message could be slightly improved in this respect.

**Comment by bobismijnnaam** [comment]
I just thought that the pointee of the variable just needed to be a heap location, but given what you said I see why it gives this error. I guess something like "...but a stack variable" or "but a function argument and hence a stack variable" would make it clearer, but maybe that's less general than the error can be so not sure if that helps. It's probably more useful to explain how perm works on the wiki and point people to that? Then at least one can see the big picture.

**Comment by wytseoortwijn** [comment]
I think _"first argument is not a heap location"_ is general enough (even though it may not be entirely clear that the error is in the `Perm(..)` predicate).

As for your suggestion on improving the explanation, I fully agree. But I suppose this falls under Issue #88, so I'll close this issue (for now).
