### ISSUE TITLE
Local variable access in pure method gives "current thread id not defined" error

### ISSUE THREAD

**Issue by bobismijnnaam** [utwente-fmt/vercors#194]
I have the following program:
```
class MyClass {
  int[] P;

  requires Perm(P, 1);
  requires P != null;
  requires (\forall* int i; 0 <= i && i < P.length; Perm(P[i], 1));
  requires (\forall int i; 0 <= i && i < P.length; 0 <= P[i] && P[i] < P.length);
  pure int getPure(int v) = get(P[v]);

  requires Perm(P, 1);
  requires P != null;
  requires (\forall* int i; 0 <= i && i < P.length; Perm(P[i], 1));
  requires (\forall int i; 0 <= i && i < P.length; 0 <= P[i] && P[i] < P.length);
  int get(int v) {
    return P[v];
  }
}

/*
class MyClass2 {
  int[] P;

  pure int getPure(int v) = get(P[v]);

  int get(int v) {
    return P[v];
  }
}
*/
```

Vercors gives the following error:

```
=== global-pure-issue.pvl          ===
   6   requires (\forall* int i; 0 <= i && i < P.length; Perm(P[i], 1));
   7   requires (\forall int i; 0 <= i && i < P.length; 0 <= P[i] && P[i] < P.length);
                                [---------
   8   pure int getPure(int v) = get(P[v]);
                                 ---------]
   9 
  10   requires Perm(P, 1);
-----------------------------------------
  Local name current_thread_id is undefined
=========================================
```

If the bottom class is uncommented it complains that ```Local name globals is undefined```. I am probably not using the language constructs correctly (am I?) but the error was somewhat puzzling to me nonetheless, since I am not using either variable name in my programs.

**Comment by wytseoortwijn** [comment]
Indeed, it is not allowed to call non-pure methods/procedures from pure ones. I agree that the error message is puzzling.

This is a problem of type checking. The type checker should complain here, but currently does not. As a result, things go wrong further down the road, when VerCors does things with the `current_thread_id ` variable while handling the invocation `get(P[v])`. (Only non-pure methods receive an extra argument `current_thread_id` during the translation to Viper).

**Comment by sjcjoosten** [comment]
We can use some help to move this forward: some examples don't work anymore because they use non-pure methods in pure methods.
