### ISSUE TITLE
Double return satisfies ensures unexpectedly

### ISSUE THREAD

**Issue by bobismijnnaam** [utwente-fmt/vercors#196]
I have the following program:

```
class MyClass {
  ensures |\result| == |xs|;
  seq<int> foo(seq<int> xs) {
    return seq<int>{};
    return xs;
  }
}
```

The verdict is pass. I'd expect it to fail, since after the first return the second one will never be executed. If you remove the second one the verdict becomes error. Wytse thinks it's because the translation to viper assigns to return variables, and hence the control flow part of return is not accounted for...?

**Comment by wytseoortwijn** [comment]
Indeed, the translated Viper output for `foo` looks like this:

```java
method method_MyClass_foo__Sequence$Integer$(diz: Ref, current_thread_id: Int, globals: Ref, xs: Seq[Int]) returns (sys__result: Seq[Int])
  requires diz != null
  requires current_thread_id >= 0
  ensures |sys__result| == |xs|
{
  var __flatten_1__1: Seq[Int]
  var __flatten_2__2: Seq[Int]
  assert !false
  __flatten_1__1 := Seq[Int]()
  __flatten_2__2 := xs
  sys__result := __flatten_2__2
  assert |sys__result| == |xs|
  inhale false
  sys__result := __flatten_1__1
  assert |sys__result| == |xs|
  inhale false
}
```

The output variable is called `sys__result` in the above. Currently, VerCors seems to generate an `inhale false` to model the `return` in the original program (indicating that after the return anything might happen). That is where the problem lies.

**Comment by niomaster** [comment]
Is the issue here not that the return statements are generated in the wrong order? In the viper output `sys__result := xs` occurs first, and as you said everything after `inhale false` doesn't matter.

**Comment by wytseoortwijn** [comment]
Indeed, I missed that: for some reason the assignments to `sys__result` seem to be switched! (but possibly with good reason). Would anything break if we generate `return` statements in "reverse" order?

**Comment by niomaster** [comment]
Found the issue; it is in this snippet of code in flatten:

https://github.com/utwente-fmt/vercors/blob/master/vercors/src/main/java/vct/col/rewrite/Flatten.java#L241-L253

Basically saying, if the first statement in a body is a return statement, instead first append all other statements and then the return statement. I can think of no reason to do that, though? It's also not stable in this example (i.e. swapping the two statements each time Flatten is run and producing the wrong result by chance).
