### ISSUE TITLE
Installation - java8 cask no longer available

### ISSUE THREAD

**Issue by Sophietje** [utwente-fmt/vercors#218]
The installation instructions for the requirements of VerCors include the following command: `brew cask install java8`
However, the cask java8 is no longer available (due to Oracle license changes?), therefore we need to update the installation instructions.

A solution can be found here: https://stackoverflow.com/questions/24342886/how-to-install-java-8-on-mac/55774255#55774255

**Comment by niomaster** [comment]
I'm running vercors in openjdk, so that should also work if that's an option for macOS
