### ISSUE TITLE
Nothing logged on unexpected exception

### ISSUE THREAD

**Issue by niomaster** [utwente-fmt/vercors#222]
If an exception propagates all the way to Main and is caught by `catch(Throwable e)`, nothing is logged to the user, only the exception is logged to the debug channel.

**Comment by sjcjoosten** [comment]
How can this be reproduced, and what is the expected / desired behavior?

**Comment by niomaster** [comment]
This only happens in the case of bugs in vercors (I encountered it while developing something), you can e.g. throw a RuntimeException somewhere to try. I think the desired behaviour is that a generic message is shown to the user ("Hey, an unexpected error occurred, please do this and report as a bug here...")
