### ISSUE TITLE
Add option<T> access methods

### ISSUE THREAD

**Issue by Sophietje** [utwente-fmt/vercors#223]
Currently an option<T> cannot be unpacked in __PVL__. It would be nice to implement methods to access/unpack values that are wrapped in an option type. In Scala you are able to use `getOrElse`, `forEach` or `match`.

See https://alvinalexander.com/scala/best-practice-option-some-none-pattern-scala-idioms for more information on how options can be unpacked in Scala.

**Comment by wytseoortwijn** [comment]
The axiomatic domain of option types is currently defined in `config/prelude.sil`, as follows:

```
domain VCTOption[T] {
  function VCTNone(): VCTOption[T]
  function VCTSome(t: T): VCTOption[T]
  function getVCTOption(o:VCTOption[T]) : T
    
  axiom not_equal_vct {
    forall x: T :: VCTNone() != VCTSome(x)
  }
  
  axiom get_axiom_vct {
    forall x: T :: getVCTOption(VCTSome(x)) == x
  }
}
```

So there is already a constructor `getVCTOption` for "unpacking" optional values, but I am not sure what the PVL equivalent of this constructor is.

Does PVL currently have a function that translates to `getVCTOption`?

**Comment by niomaster** [comment]
We want to map some operator to `StandardOperator.OptionGet`, from there it is indeed translated to a viper function. Nothing maps to `OptionGet` yet in PVL (or any other language), so we just need to decide on a syntax. Any suggestions? Or do we want to go the functional route, as Sophie suggests?

**Comment by OmerSakar** [comment]
After a discussion, it was decided that we will go for the following syntax: `o1.get()` and `o1.getOrElse(defaultValue)`

**Comment by OmerSakar** [comment]
After some more discussion, it was decided to leave the syntax mentioned in the previous comment in favour of `getOption(o1)` and `getOrElseOption(o1,default)`.
