### ISSUE TITLE
No output upon verification (or error when using a loop)

### ISSUE THREAD

**Issue by Sophietje** [utwente-fmt/vercors#227]
So I was trying to verify some program but it did not generate any output. Even though I would at least expect something like "Pass" or "Fail". The program was as follows:
```
class MyClass {
	ensures \result == a^^n;
	int exp(int a, int n){
	}
}
```
The __cause seems to be the ensures clause__ (perhaps the ^^ operator?), when this is removed then it does give a final verdict.

Moreover, when the example is extended with a loop inside the method, then it will result in the following error (the error has been compacted):
```
Please do not write to stdout or stderr explicitly! You are welcome to leave debugging information in, but use hre.lang.System.Debug instead. If you must use a stream, use hre.lang.System.getLoggingLevelOutputStream instead.
at Thread.java:1559
at ForbiddenOutputStream.java:19
...
```
This error was caused by the following program:
```
class ExplicitHoareProofTest {
	requires a >= 0 && n >= 0; 
	ensures  \result == a^^n;
	ensures false;
	int exp(int a, int n){ 
		int k; 
		int z; 
		k = 0;
		z = 1;
		loop_invariant z == aˆˆk && k <= n && a >= 0;
		while (k != n) {
			z = z * a;
			k = k + 1;
		}
		return 
	}
}
```

**Comment by Sophietje** [comment]
Marieke found another example (I have minimized the example for this issue) where the exact same error is reported:

```
class KernelEncoding {
  invariant a != null;
  void bla (int [] a) {
     par (int tid = 0 .. a.length)
       // solved by       
       // context tid > 0 ==> Perm(a[tid], 1/2);
       // context tid == 0 ==> Perm(a[tid], write);
       context tid > 0 ? Perm(a[tid], 1/2) : Perm(a[tid], write);
    {
		// do something... 
    }
  }
}	
```

In this case it seems to be caused by the context clause in the parallel block with the inline if-statement.

**Comment by wytseoortwijn** [comment]
The latter example gives the following error:

> Verification aborted exceptionally: java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: scala.MatchError: acc(getVCTOption1(a)[tid].Integer__item, 1 / 2) (of class viper.silver.ast.FieldAccessPredicate)
>   Cause: java.util.concurrent.ExecutionException: scala.MatchError: acc(getVCTOption1(a)[tid].Integer__item, 1 / 2) (of class viper.silver.ast.FieldAccessPredicate)

So this seems a bug in Viper. We should update the Viper back-end of VerCors to see if this resolves the problem. Otherwise, we should contract the Viper developers.

**Comment by wytseoortwijn** [comment]
For the very first example, VerCors gives:

> Triggered by file examples/test/test30.pvl from line 2 column 21 until line 2 column 24:
> hre.lang.HREError: cannot map operator Exp
> 	at vct.silver.SilverExpressionMap.map(SilverExpressionMap.java:156)
> 	at vct.col.ast.OperatorExpression.$anonfun$accept_simple$2(OperatorExpression.scala:57)
> 	at vct.col.util.VisitorHelper.handle_standard(VisitorHelper.scala:21)
> 	at vct.col.util.VisitorHelper.handle_standard$(VisitorHelper.scala:21)
> 	at vct.col.ast.OperatorExpression.handle_standard(OperatorExpression.scala:7)
> 	at vct.col.ast.OperatorExpression.accept_simple(OperatorExpression.scala:57)
> 	at vct.col.ast.ASTNode.apply(ASTNode.java:185)
> 	at vct.silver.SilverExpressionMap.map(SilverExpressionMap.java:75)
> 	at vct.col.ast.OperatorExpression.$anonfun$accept_simple$2(OperatorExpression.scala:57)
> 	at vct.col.util.VisitorHelper.handle_standard(VisitorHelper.scala:21)
> 	at vct.col.util.VisitorHelper.handle_standard$(VisitorHelper.scala:21)
> 	at vct.col.ast.OperatorExpression.handle_standard(OperatorExpression.scala:7)
> 	at vct.col.ast.OperatorExpression.accept_simple(OperatorExpression.scala:57)
> 	at vct.col.ast.ASTNode.apply(ASTNode.java:185)
> 	at vct.silver.VerCorsProgramFactory.convert(VerCorsProgramFactory.java:238)
> 	at vct.silver.VerCorsProgramFactory.convert(VerCorsProgramFactory.java:37)
> 	at vct.silver.SilverBackend.TestSilicon(SilverBackend.java:118)
> 	at vct.main.Main$9.apply_pass(Main.java:694)
> 	at vct.main.Main.main(Main.java:604)
> entire run took 2499 ms

Here the problem is different: the `^^` operator does not seem to be translated to valid Viper output. We should find out if Viper (natively) supports `^^`.

**Comment by Sophietje** [comment]
I cannot find anything about the ^^ operator being supported in Viper. In their tutorial they mention that the following operators are allowed in integer expressions: addition, subtraction, multiplication, division and modulo. No exponential operator is mentioned here nor can I find it in M. Schwerhoff's thesis.

**Comment by niomaster** [comment]
I fixed the first case in https://github.com/utwente-fmt/vercors/pull/253. Just for future reference, if you get an error of the type "Please do not write to stdout or stderr explicitly!", that's because you shouldn't write to stdout or stderr explicitly :^). I tried to remove every instance of "System.out.println", but some do fall through the cracks. In this case the PVL lexer still had the default error handler, so it tried to write to stdout. If someone finds another instance of this, please make a separate issue, as it likely does not have the same cause.

**Comment by niomaster** [comment]
The second case is due to #243

**Comment by niomaster** [comment]
Which leaves the exponentiation operator, what do we want to do about that?

**Comment by raulmonti** [comment]
If needed we can define a method in viper with a recursive contract to implement ^^.

**Comment by niomaster** [comment]
@Sophietje, do you still need the exponentiation operator?
