### ISSUE TITLE
Java version test problems with Java 11

### ISSUE THREAD

**Issue by mgudemann** [utwente-fmt/vercors#235]
When trying to run vercors using Java 11
(exact version ```openjdk version "11.0.3" 2019-04-16
OpenJDK Runtime Environment (build 11.0.3+7-Ubuntu-1ubuntu218.04.1)
OpenJDK 64-Bit Server VM (build 11.0.3+7-Ubuntu-1ubuntu218.04.1, mixed mode, sharing)```)

I get the error
```
Buildfile: /home/plain/VSTA2019/vercors/build.xml

compile:
     [exec] 
     [exec] The java installation you have is not up to date
     [exec] requires at least version 1.6+, you have
     [exec] version 11.0.3
     [exec] 
     [exec] Please go to http://www.java.com/getjava/ and download
     [exec] a valid Java Runtime and install before running .
     [exec] 

BUILD FAILED
/home/plain/VSTA2019/vercors/build.xml:40: exec returned: 1
```

**Comment by niomaster** [comment]
Thank you for reporting! This seems to be related to https://github.com/utwente-fmt/vercors/issues/197
