### ISSUE TITLE
Illegal iteration invariant

### ISSUE THREAD

**Issue by Sophietje** [utwente-fmt/vercors#241]
Marieke found an example that results in an error message regarding an illegal iteration invariant. The cause seems to be that the keyword invariant incorrectly places checks in the nested blocks. It occurs in the following program (the cause is the invariant about permissions):
```
class Max {
  invariant a != null;
  invariant pow >= 0;
  invariant (\forall* int j; 0 <= j && j < a.length; Perm(a[j], write));
  void maxInPlace(int [] a, int pow) {
     int round = 0;
     int exp = 1;
     loop_invariant 0 <= i && i <= pow;
     loop_invariant 1 <= exp && exp <= a.length;
     for (int i = 0; i < pow; i++) {
       par (int tid = 0 .. a.length/exp)
	   {
       }
       exp = 2 * exp;  
     }
 }
} 
```

If you remove the parallel block then the error does not occur.

The specific error that it produces:
```
At file save-max-in-place.pvl from line 12 column 12 until line 14 column 8: illegal iteration invariant at file save-max-in-place.pvl from line 5 column 13 until line 5 column 71
The final verdict is Error
```

If you replace the invariant by a context clause before the method, a loop_invariant for the for-statement and a context for the parallel block, then the tool does not report any "illegal iteration invariant".

**Comment by Sophietje** [comment]
If you have a look at the intermediate representation that is sent to viper, then it shows that the parsing failed.

**Comment by niomaster** [comment]
The invariants are copied into the parallel block as well, so the end result would be that all threads from the parallel block require `(\forall* int j; 0 <= j && j < a.length; Perm(a[j], write))`, for which there is insufficient permission. The error seems to be there to prevent you from making that mistake, specifically it is forbidden to write invariants that involve permissions in the presence of parallel blocks.

Should the behaviour be something else?

**Comment by sjcjoosten** [comment]
Perhaps we can use the type checker's distinction between booleans and resources to decide if we want to copy an invariant to a parallel block: if it's a boolean, copy it, if it's a resource, don't. I think that would make the most sense in most cases.

**Comment by niomaster** [comment]
I don't really like that solution, as that would mean that

```
invariant forall x . a ** b
```

and

```
invariant forall x . a
invariant forall x . b
```

are treated differently when a is a resource, b is a boolean.

**Comment by niomaster** [comment]
We decided to go with @sjcjoosten's solution: copy booleans to parallel blocks, but not resources.

**Comment by petravandenbos-utwente** [comment]
Here's another example with the same problem:
```
class ParNotWorking {

	int x, y;
	
	ensures Perm(x,1);
	ensures Perm(y,1);
	ParNotWorking() {
		x = 3;
		y = 5;
	}
		
	context_everywhere Perm(x,1);
	context_everywhere Perm(y,1);
	void bla() {
		par
		{
			x = x -1;
		} and
		{
			y = y - 1;
		}
	}
		
}
```
The error message is:
```
At file examples/private/ParInRun.pvl from line 16 column 2 until line 18 column 2: illegal iteration invariant at file examples/private/ParInRun.pvl from line 12 column 20 until line 12 column 28
The final verdict is Error
```

A work-around is to not use context_everywhere:
```
class ParWorking {

	int x, y;
	
	ensures Perm(x,1);
	ensures Perm(y,1);
	ParWorking() {
		x = 3;
		y = 5;
	}
		
	context Perm(x,1);
	context Perm(y,1);
	void bla() {
		par
		context Perm(x,1);
		{
			x = x -1;
		} and
		context Perm(y,1);
		{
			y = y - 1;
		}
	}
		
}
```

**Comment by niomaster** [comment]
`context_everywhere` is now appropriately scaled down in parallel blocks (so divided by 2 in `par / and`, divided by N within a par-block from 0..N and so on)
