### ISSUE TITLE
Clearer indication of missing permissions

### ISSUE THREAD

**Issue by Sophietje** [utwente-fmt/vercors#247]
It can be very difficult to identify missing permissions when the tool shows an "InsufficientPermission" error.

Take for example the following code:
```
class KernelEncoding {
  given int [] a_in;
  invariant a != null;
  requires a_in != null && a_in.length == a.length;
  context (\forall* int i; 0 <= i && i < a.length; Perm(a_in[i], read));
  context (\forall* int i; 0 <= i && i < a.length; Perm(a[i], write));
  requires (\forall* int i; 0 <= i && i < a.length; a[i] == a_in[i]);
  ensures a[0] == a_in[0];
  void bla (int [] a) {
    a[0] = a_in[0];
  }   
}
```

The verifier will tell you that you have insufficient permissions to verify the ensures clause. However, if you read the context-clauses, then you would expect to have all permissions. After all, you said you require/ensure permission from index i=0 to i=a.length for both arrays.
The issue in this case is however that a.length may be 0 therefore we also need to specify that `invariant a.length > 0`
A more precise error, or possibly a hint about what the issue may be, can alleviate this problem.

**Comment by sjcjoosten** [comment]
We believe that asserting that 0 is within range (i.e. `0 <= 0` and `0 < a.length`) would help yield a good error message in this case. The error message could be: cannot assert that `0<a.length`, which is needed to ensure that `0` is within bounds in a[0].

**Comment by niomaster** [comment]
Maybe we could use a similar approach as with options here, not using the domain function (`loc`) directly, but instead using a function with some preconditions that refers to the domain function. Something like:

```
domain Array[CT] { function loc(a: Array[CT], i: Int): CT }
function loc1(a: Array[CT], i: Int): CT
  requires 0 <= i && i < alen(a)
{
  loc(a, i)
}
```

**Comment by sjcjoosten** [comment]
Looks good! Let's split the two requires in separate lines, and add the postcondition `\result = loc(a,i)`.

**Comment by niomaster** [comment]
We have array bounds checking now!
