### ISSUE TITLE
SonarCloud enum style rule

### ISSUE THREAD

**Issue by niomaster** [utwente-fmt/vercors#248]
[This](https://sonarcloud.io/organizations/utwente-fmt/rules?open=squid%3AS00115&rule_key=squid%3AS00115) style rule specifies that enum values should consist of capitals and underscores. In e.g. StandardOperator we instead do capitalized camelcase, so I think we should just change the rule to that.

**Comment by niomaster** [comment]
I also would like to remark that the sonarcloud integration is proving quite useful so far! Couple of useful warnings were generated.

**Comment by Sophietje** [comment]
I have created a copy of the Sonar quality profile (called "VerCors Java profile") which is now enabled. This quality profile is exactly the same as the Sonar quality profile with the rule about the naming convention of constants deactivated. I expect that this is now fixed.

**Comment by niomaster** [comment]
@Sophietje can you check whether this is now resolved?
