### ISSUE TITLE
Use SonarCloud rule instead of HRE check

### ISSUE THREAD

**Issue by sjcjoosten** [utwente-fmt/vercors#263]
Issue #243 because Viper wrote to stdout. In such cases, we do want to see the stdout, but we also wish to forbid any code that writes to stdout. The current solution is to hide the stdout and crash. It would be better to be a bit more subtle: show the stdout first and then crash eventually (perhaps whenever a 'check' pass happens), and use SonarCloud to make sure that people don't misuse this to do their error reporting.

In any case, this issue is there to remind us that we make a SonarCloud rule that forbids doing stdout anywhere (except via HRE). If the rule fires, it should specifically mention that for the VerCors project, HRE should be used instead of stdout.

**Comment by niomaster** [comment]
We use a standard logging framework these days, and `println` is not explicitly banned anymore.
