### ISSUE TITLE
Verification aborted exceptionally for simple java code that uses fold/unfold

### ISSUE THREAD

**Issue by raulmonti** [utwente-fmt/vercors#268]
**This is the code:**

```
public class A{
	int[] a;

	/*@
		resource R(int i) = Perm(a,1) ** true;
	@*/


	/*@ 
		requires R(1);
	@*/
	public void F(){
		//@ refute(false);
		//@ unfold(R(1));
		//@ fold(R(1));
		assert true;
	}
}
```

**This is the output:**

`
Verification aborted exceptionally: java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: java.util.NoSuchElementException: None.get
  Cause: java.util.concurrent.ExecutionException: java.util.NoSuchElementException: None.get
Errors! (1)
[warning] unspecified error exceptional.error
The final verdict is Fail
`

_The problem seems to be related to how the JavaEncode pass is done. An equivalent code in pvl shows no problems at all._

**Comment by niomaster** [comment]
Maybe you can comment on the correct approach here @bobismijnnaam ?

**Comment by bobismijnnaam** [comment]
We should properly implement support for APFs, then this will give a sensible error message. It can be worked around by marking the resource R as final, since then the dynamic type does not need to be known in this case and it can be unfolded whenever.
