### ISSUE TITLE
Negative permissions when using read in for loop

### ISSUE THREAD

**Issue by raulmonti** [utwente-fmt/vercors#272]
**The following code returns an unexpected error (detailed below)**
```
class Element{

	int atribute;

	Element(int a){
		this.atribute = a;
	}
}


class Issue{

	invariant array != null;
	invariant Perm(array[*], read);
	invariant (\forall* int i ; 0 <= i && i < array.length ; Perm(array[i].atribute, read));
	int first_zero(Element[] array){
		int result = -1;
	
		loop_invariant i >= 0 ** i <= array.length;
		for(int i = 0; i < array.length; i++){
			if(result == -1 && array[i].atribute == 0){
				result = i;
			}
		}
		return result;
	}
}
```

**The result for _vct --silicon \<file with above code\>_ throws**
```
[warning] unspecified cause negative.permission
=== issue.pvl                      ===
  15 	invariant array != null;
  16 	invariant Perm(array[*], read);
               [-----------------------------------------------------------------------------
  17 	invariant (\forall* int i ; 0 <= i && i < array.length ; Perm(array[i].atribute, read));
                -----------------------------------------------------------------------------]
  18 	int first_zero(Element[] array){
  19 		int result = -1;
-----------------------------------------
  InvariantNotEstablished:UnspecifiedCause
=========================================
=== issue.pvl                      ===
  15 	invariant array != null;
  16 	invariant Perm(array[*], read);
                                                                                      [----
  17 	invariant (\forall* int i ; 0 <= i && i < array.length ; Perm(array[i].atribute, read));
                                                                                       ----]
  18 	int first_zero(Element[] array){
  19 		int result = -1;
-----------------------------------------
  caused by
=========================================
The final verdict is Fail
```

**The error is not there when we replace the "read" permission for "1/2" permission for instance.**

**Comment by wytseoortwijn** [comment]
Workaround: changing the first `invariant` line to `invariant array != null && 0 <= array.length;` fixes it on my slightly older version of VerCors. I'm not sure why though...

**Comment by wytseoortwijn** [comment]
I looked a little bit further. I'm still not sure where the problem is exactly, but it seems that Viper has some difficulties with handling the current encoding of arrays.

When I look at the generated Viper code, I see that VerCors generates and uses the following auxiliary function:
```
function getVCTOption1(x: VCTOption[Seq[Ref]]): Seq[Ref]
  requires x != VCTNone() 
{
  getVCTOption(x)
}
```

To me this looks weird: why not use `getVCTOption(x)` directly? In any case if I replace all occurrences of `getVCTOption1` by `getVCTOption` in the Viper output it passes.

I suggest, perhaps in a separate issue, to either remove the generated `getVCTOption1` function, or otherwise to find out why it is needed (perhaps it's there for good reason, but for this particular example it seems to hamper analysis).

**Comment by raulmonti** [comment]
None of the two solutions that work for you work in my version of VerCors :S What it does work is to change the `wildcard` permissions in the generated viper code to `1/2` permissions, and removing some syntax mistakes (I get a method named `method_Issue_first_zero__Option<Array<Cell<Element>>>` for which Viper complains, but I guess that it is a VerCors mistake and should be replaced for something like `method_Issue_first_zero__Option_Array_Cell_Element`?

**Comment by niomaster** [comment]
`read`/`wildcard` can lead to proof failures quite quickly in non-trivial cases, but this is mostly a proof technique and/or viper issue.
