### ISSUE TITLE
Renaming Vercors-keyword invariant

### ISSUE THREAD

**Issue by sjcjoosten** [utwente-fmt/vercors#278]
In VerCors, we have currently implemented the keyword ``invariant``, which is unfortunate because it deviates from what this word means elsewhere (like in JML). We decided  renaming ``invariant`` to adding an optional argument to ``context``, with the value ``everywhere``. I propose the syntax ``context[everywhere]`` because I foresee the least parsing issues with this. If there are parsing issues, I would find ``context_everywhere`` would be acceptable. Feel free to join in a discussion about syntax here.

Aside from the parser, also the examples need to be changed as well.

**Comment by sjcjoosten** [comment]
What's the new keyword?

**Comment by raulmonti** [comment]
I believe that `context_everywhere` is the new one
