### ISSUE TITLE
Pointer permisison syntax

### ISSUE THREAD

**Issue by niomaster** [utwente-fmt/vercors#285]
In C we can specify the validity of pointers with `\pointer(x, N, write)` and such. In parallel blocks and loops, we often just want permission on `x[i]`, which necessitates writing it as something like `\pointer(&x[i], 1, write)`, which looks a little silly. 

`\pointer(x, N, p)` is syntactic sugar (roughly) for `x != NULL ** x.length >= N ** (\forall i \in [0..N] . Perm(x[i], p))`. For just one element at `i` we would still need `x != NULL ** x.length >= i`, but just `Perm(x[i], p)`, so maybe a syntax for just one element would be good. `\pointer_at(x, i, write)`, maybe? Or does someone have another suggestion?

**Comment by raulmonti** [comment]
Other options with out changing the **\pointer** keyword:
- Changing the number of parameters:
`\pointer(x[i], p)` for a single place
`\pointer(x+i, p)` for a single place
- Changing the type and meaning of the second parameter:
`\pointer(x, n..m, p)` for chunk of memory access
`\pointer(x, n, p)` for single place

**Comment by wytseoortwijn** [comment]
I haven't followed the discussions regarding C support, but why not simply support the following annotations instead of `\pointer`?

```C
requires Perm(*p, write);
void foo(int *p) {
}

requires (\forall* int i; 0 <= i && i < n; Perm(*A[i], write));
void bar(int *A, int n) {
}
```

**Comment by niomaster** [comment]
These certainly are supported, but don't show `p != NULL` and that `len(p)` is at least whatever you need. I'm hesitant to let you specify the length of the pointer explicitly, as it represents the true length of valid data, whereas you really only need to specify that you have enough.

In the meeting today we decided that `pointer_index(pointer, index, permission)` would be a good option.
