### ISSUE TITLE
Building with giving commands not working

### ISSUE THREAD

**Issue by feeverts** [utwente-fmt/vercors#29]
Using git bash on windows 10
installed java jdk and set the java dir to the jkd install folder

[log.txt](https://github.com/utwente-fmt/vercors/files/603441/log.txt)

**Comment by sccblom** [comment]
It looks like the build was succesful, but the unix script is not working with your git bash.

If you use the windows terminal, does the windows script path-to-vercors\windows\bin\vct  work?

**Comment by feeverts** [comment]
That worked.

./windows/bin/vct.cmd --test=examples/manual --tool=silicon --lang=pvl,java
