### ISSUE TITLE
Syntax errors when using brackets

### ISSUE THREAD

**Issue by wytseoortwijn** [utwente-fmt/vercors#295]
The parser doesn't currently handle brackets (probably left-expressions in general) correctly. For example, the following two assertions both produce syntax errors:

```java
requires 0 < |xs|;
void test1(seq<int> xs, seq<int> ys) {
  assert xs[0] == (xs + ys)[0]; // syntax error 1
  assert xs[0] == \old(xs)[0]; // syntax error 2
}
```

I find this a very restricting bug.

**Comment by niomaster** [comment]
I'm almost done cleaning up the expression grammar in PVL, but there's one expression type that I don't quite understand:

```
atomExpression
 : target '->' identifier tuple
```

It looks like it maps to this code in PVLtoCOL:

```
if(match(ctx,null,"->",null,tuple)){
  ASTNode args[]=getTuple((ParserRuleContext)ctx.getChild(3));
  String method=getIdentifier(ctx,2);
  ASTNode object=convert(ctx,0);
  return create.expression(StandardOperator.Implies,
    create.expression(StandardOperator.NEQ,object,create.reserved_name(ASTReserved.Null)),
    create.invokation(object,null, method, args)
  );
}
```

It looks a little bit like a [null-conditional operator](https://docs.microsoft.com/en-gb/dotnet/csharp/language-reference/operators/member-access-operators#null-conditional-operators--and-), but maybe someone can tell me.

**Comment by wytseoortwijn** [comment]
@niomaster Looks to me as C++ style method invocation or so, like in
```C++
class Foo {
  public:
  void bar();
}

void test(Foo* f) {
  f->bar();
}
```
with an extra check to ensure that `f` is not `null`, using implication.
