### ISSUE TITLE
invariant vs context_everywhere

### ISSUE THREAD

**Issue by wytseoortwijn** [utwente-fmt/vercors#303]
I noticed that the keyword "invariant" has recently been renamed into "context_everywhere". Note that previously "invariant" could be used in (at least) two different ways, namely **(1)**:
```java
invariant P;
void foo() {
   ...
}
```

but also **(2)**:

```java
void foo() {
  invariant inv(P) {
    par (int tid = 0 .. N) {
      atomic (inv) {
        ...
      }
    }
  }
}
```

I don't think renaming "invariant" into "context_everywhere" in scenario **(2)** is an improvement. I think "invariant" fits much better here than "context_everywhere". Actually, I think that renaming it here is wrong.

In scenario **(1)** it makes sense to rename "invariant" to "context_everywhere", because the annotated property `P` was not actually an invariant. But in scenario **(2)** it *is* actually an invariant (something that is called a resource invariant in CSL).

Any further thoughts on this?

**Comment by niomaster** [comment]
We discussed and agree with you. We should distinguish between these two cases and change back context_everywhere in the resource invariant case.
