### ISSUE TITLE
Unsatisfiable requires, possible warning?

### ISSUE THREAD

**Issue by bobismijnnaam** [utwente-fmt/vercors#308]
Currently the following code verifies:

```
final class MyClass {
    public static int foo;

    //@ requires Perm(MyClass.foo, 1);
    public static void eat() {}

    //@ requires Perm(MyClass.foo, 1) ** Perm(MyClass.foo, 1);
    //@ ensures Perm(MyClass.foo, 1) ** Perm(MyClass.foo, 1);
    public static void main() {
        foo = 2;
        eat();
        eat();
        //@ assert 1 == 2;
    }
}
```

I think it boils down to the fact that the requires in this case is false indirectly. In the most cases I expect at least a warning (```warning: requires might be unintentionally unsatisfiable```), at most an error (```error: requires must be satisfiable```). 

The only cases that I can come up with where ```requires false;``` could be useful is in the context of inheritance, or if you want to exclude a method from verification. E.g. ```ImmutableArrayList extends ArrayList```, and then give ```add()``` a ```requires false;``` to indicate it must never be called when casted. The second case can actually be useful if you want to have some "dirty" code in your class. However, in both cases I think a warning would still be okay, or maybe an annotation can be required to suppress the error (since these cases are the exception, so it should not happen too often anyway).

In theory checking satisfiability in something like Z3 is pretty standard, but I don't know how to do it in Viper.

**Comment by wytseoortwijn** [comment]
I think there was a special annotation for this in earlier versions of VerCors. Something like `refute false`. There was even a special flag that one could give to VerCors in order to automatically check for these things. But at some point support got dropped for some reason. Perhaps you could try to revive it.

This ultimately boils down to the classical question of whether the specification is correct or not. You could add such checks to provide the user with a sort-of sanity check. But on the other hand, it would also be reasonable to let correctness of the specifications be the responsibility of the user, and not of VerCors (meaning that VerCors doesn't have to give a warning).

**Comment by bobismijnnaam** [comment]
@wytseoortwijn Can you give an indication of how long ago it was, so I know where to start looking? 1 years ago, or 5?

**Comment by wytseoortwijn** [comment]
I'd say 3 years, perhaps 2.

**Comment by bobismijnnaam** [comment]
Small progess report: turns out the check is still in there, under name of the pass `sat_check`. This pass introduces `refute false` at the beginning of every method. This correct behavior, but it seems that currently the `refute` statement is broken. I think this happened because the way passed/rejected methods were reported back from the viper api changed, and because the refutes are currently encoded as `assert !e`, which is only partially correct. 

Two ways to solve this:
1. Fix `refute`
2. Reimplement `sat_check` to create extra methods, copying the contract but inserting `assert false` as body. When these asserts trigger, it means the contract is verifiable. When they don't, it means the contract cannot be satisifed (maybe with an exception for `requires false` for utility). 

I can do option 2, but 1 might be a bit more involved, and also more of a project wide issue. For now I will get started on 2, as it seems orthogonal to option 1, if that's okay.

**Comment by bobismijnnaam** [comment]
After two brief discussions with Raul and Pieter we settled on implementing the second option, except not by adding extra methods but by putting the `assert false` at the end of the method. The following:
```
int boo() {
    while (true) {}
}
```
Will be encoded into:
```
method boo() returns (ret: Int) {
    var b: Bool;
    if (b) {
        while (true) { }
    } else {
        assert false;
    }
}
```
Since `b` is uninitialized both branches must be checked. If `boo` follows its specification and its `requires` is satisfiable, the only error to be found is the extra added assert. The extra `if` is needed because if you leave it out the added `assert false` will not be flagged because the while loop does not terminate. This makes the generated SIL more concise as it keeps the contract checking local to the method, instead of generating extra auxiliary methods.

If there are no objections I will work on implementing this next week.

**Comment by wytseoortwijn** [comment]
I don't see why you would want to put an `assert false` at the end of a method like this (but I missed the discussions).

If you want to test whether preconditions are satisfiable, why not encode these checks as separate functions/methods, or externally altogether?

**Comment by wytseoortwijn** [comment]
But perhaps it is better to test the satisfiability of an assertion `P` in a separate method, as `inhale P; exhale false` or so? Not sure.

But this is ultimately just a sanity check: if `inhale P; exhale false` verifies, then `P` is unsatisfiable. If it doesn't verify, then you don't know anything.

**Comment by bobismijnnaam** [comment]
@wytseoortwijn I agree that it's probably best to do the check in a separate method. It seems the other workarounds introduce some tricky edge cases.

**Comment by niomaster** [comment]
Just a comment; I think it's good to have a flag for this feature (either to disable or to disable it, I have no opinion on what the default should be). I spend quite some time looking at viper output and seeing what vercors does wrong now, so having to dig through expected errors would be quite cumbersome in that case :)

**Comment by bobismijnnaam** [comment]
Yes, will do!
