### ISSUE TITLE
Atomics with lock invariants

### ISSUE THREAD

**Issue by wytseoortwijn** [utwente-fmt/vercors#313]
The following snippet doesn't verify at the moment, yet would be desirable:
```java
class Cell {
  int val;

  resource lock_invariant() = Perm(val, 1/2);

  ensures Perm(val, 1/2);
  Cell() {
  }
	
  context Perm(val, 1/2);
  void incr(int n) {
    atomic(lock_invariant) {
      val = val + n;
    }
  }
}
```

The problem is that `atomic` doesn't work together with `lock_invariant`. Replacing `atomic { ... }` with `lock this; ...; unlock this;` would make it verify though.

**Comment by sjcjoosten** [comment]
Would it be okay if we were to write the following instead:

```java
class Cell {
  int val;

  resource lock_invariant() = Perm(val, 1/2);

  ensures Perm(val, 1/2);
  Cell() {
  }
	
  context Perm(val, 1/2);
  void incr(int n) {
    atomic(this) { // I changed this line
      val = val + n;
    }
  }
}
```

Using this approach provides better scoping: the atomic actions then only need to be atomic wrt the object mentioned, allowing for parallelisation of atomic actions that are not related. For your example, executing ``incr(n)`` on two different ``Cell`` instances does not need any synchronisation, while from your previous example it is impossible to see this and the only suitable semantics for atomics would be to use a global lock (in a runtime without an atomic 'add').

**Comment by wytseoortwijn** [comment]
That would be OK as well. Better even!

**Comment by wytseoortwijn** [comment]
The thing is that PVL supports both statically-scoped locking (`atomic`) and dynamically-scoped locking (`lock; unlock`). But these two are very separated: they can't be mixed up.

**Comment by wytseoortwijn** [comment]
Perhaps one could also consider adding support for constructs as:
```java
context Perm(val, 1);
void incr(int n) {
  invariant inv(Perm(val, 1/2)) {
    lock this;
    val = val + n;
    unlock this;
  }
}
```

(Not sure if this would work though.)

**Comment by raulmonti** [comment]
Wytse, would there be a good use case for this last suggestion? If so, please create a new issue with the use case. Marieke

**Comment by sjcjoosten** [comment]
The suggested solution to this issue is to rewrite:

```
    atomic(a) { 
      S
    }
```

into:

```
    lock(a);
    S
    unlock(a);
```

**Comment by wytseoortwijn** [comment]
@raulmonti None at the moment. Just came to mind. I'll drop it for now.
