### ISSUE TITLE
"Possible simplification failure" warnings

### ISSUE THREAD

**Issue by niomaster** [utwente-fmt/vercors#328]
Hi, do any of you find the "possible simplification failure" warnings useful / too verbose? I'm not sure exactly what they mean, I'm guessing they are related to the simplify_quant pass (jspec rules), but not sure what heuristic is used for a simplification "failure". If nobody finds them useful I think we should remove them.

**Comment by wytseoortwijn** [comment]
One can also get "simplification failure"s instead of mere "possible simplification failure".

I don't find the exact messages very useful. But every time I get such warnings I try to find ways to get rid of them. I often interpret such warnings roughly as "you're now on the edge of what VerCors can handle" (even though that's not entirely accurate). So far this has been useful information for me.

**Comment by niomaster** [comment]
Thanks, @wytseoortwijn 

Here is the heuristic for consideration. This is from `SilverExpressionMap`, so in fact the warning is generated only just before an AST is delivered to viper. A `BindingExpression` with binder `Star` represent a `\forall*`.

```
  public E map(BindingExpression e) {
    Origin o = e.getOrigin();
    switch (e.binder) {
    case Star:
      if ((e.main instanceof BindingExpression)||e.getDeclarations().length>1){
        hre.lang.System.Warning("Simplification failure: %s",e);
        failure=true;
      } else {
        boolean good=false;
        if (e.main.getType().isBoolean()){
          good=true;
        } else if (e.main.isa(StandardOperator.Perm)||e.main.isa(StandardOperator.Value)){
          ASTNode loc=((OperatorExpression)e.main).arg(0);
          while (loc instanceof Dereference){
            loc=((Dereference)loc).obj();
          }
          if (loc.isa(StandardOperator.Subscript)){
            loc=((OperatorExpression)loc).arg(1);
            good=loc instanceof NameExpression;
          }
        }
        if(!good){
          hre.lang.System.Warning("Possible simplification failure: %s",e);
        }
      }
```

**Comment by niomaster** [comment]
As they're at least somewhat useful let's let them in. I think the intention of the heuristic is to exclude the obvious simple quantifier for a one-dimensional array, so I've fixed that with Henk's array implementation in #338 (There's a missing `getOption` there, and `Subscript` is translated to an invokation)

**Comment by petravandenbos-utwente** [comment]
A matrix ```int[][] matrix``` also gives this warnings, and VerCors has no problems with verifying my matrix program.
