### ISSUE TITLE
Models instead of futures

### ISSUE THREAD

**Issue by raulmonti** [utwente-fmt/vercors#370]
We talked about changing the keyword for model classes that are used for working with futures. We should be able to define a `model` and we should be able to give it an arbitrary name. I understand that, in contrast, the actual implementation requires to write a class named "Future". 

>It was also suggested to change the way we describe the models using a process algebra instead of the class description they get now. I think this was in line with integrating the whole process of futures into some Model Checker tool such as MCRL2. We can solve that in a separated issue but I just wanted to clear out where we are going.

**Comment by niomaster** [comment]
The syntax is now changed.
