### ISSUE TITLE
Non-standard java grammar element

### ISSUE THREAD

**Issue by niomaster** [utwente-fmt/vercors#373]
Hi all,

I came across this in the java grammar:

```
explicitGenericInvocationSuffix
    (...)
    |   javaIdentifier ('@' javaIdentifier )? arguments
    ;
```

What does the `@` mean? There is some example usage e.g. here: https://github.com/utwente-fmt/vercors/blob/dev/examples/threads/Worker.java#L22

**Comment by Sophietje** [comment]
This reminds me of what Bob told me about abstract family predicates (I
think this was the term, not 100% sure). It has also been added in a commit
for "inheritance examples" so it seems reasonable to assume that it has to
do with inheritance.
