### ISSUE TITLE
Exclusive history flags break examples and unexpected behavior

### ISSUE THREAD

**Issue by bobismijnnaam** [utwente-fmt/vercors#374]
Currently the flags `--check-history` and `--check-defined` (and probably also `--check-axioms`) are intended to be used in a mutually exclusive manner, but this is not enforced. Combining them causes (to me) unexpected behavior. For example, in the example `demo/demo4.pvl` both options are listed. If only the first one is used (`--check-history`) the example fails with an error. If only the second is used, verification succeeds (trivially, it seems). If they are both used, verification succeeds as well, because `--check-defined` overrides `--check-history`. I would expect verification to fail if one of the used flags fail, or at least warn me if results are possibly hidden. This is important for CI to detect regressions.

I think we have three options:

- Warn on use of combination of the three flags. Leave the behavior as it is now.
- Error on use of combinations, allowing use of only one of the three at all times.
- Actually do a separate run of vercors for each of the used flags, such that the flags do not influence/hide errors from eachother.

If a nice format can be invented for displaying results from all three of the flags separately in a log, I think option three is the best option. However since this might be difficult option 2 is probably better, since it simplifies usage of vercors and its output, and is straightforward to implement. The only downside is this might make CI for examples with multiple `--check-*` flags harder... Thoughts?

**Comment by bobismijnnaam** [comment]
For now I removed the `--check-defined` flag such that regressions of `--check-history` are detected properly in #379. However now `--check-defined` is not executed for this file, so we still need a proper fix.

**Comment by wytseoortwijn** [comment]
Option 2 would be fine. Option 3 would be ideal.

The `--check-history` flag is used to check whether the program correctly implements the process-algebraic specification. The `--check-defined` flag check whether the process-algebraic specification itself satisfies its contract.

Hmmm, with my slightly older version of VerCors the `--help` flag doesn't give meaningful information on these flags. When I run `vct --help` I get:

```
...
 --check-defined       : check if defined processes satisfy their contracts.
 --check-axioms        : check if defined processes satisfy their contracts.
 --check-history       : check if defined processes satisfy their contracts.
...
```

**Comment by bobismijnnaam** [comment]
Do there exists input programs where if one of the `--check-*` flags would cause vercors to fail and the remaining two `--check-*` flags would succeed, that then the program can still considered to be correct? Or is it the case that for any program using futures, it can only be considered correct if vercors can successfully verify all three flags?

If the latter case is correct, then there's also option 4: only allow all three to be run at once (i.e. replace them with _one_ flag, `--check-futures`) and don't allow invoking them separately, since they all need to be verified for the program to be correct anyway. Or detect when futures are used, and then invoke all three of the flags? Unless invoking them separately is what is usually done for performance reasons or something.

**Comment by wytseoortwijn** [comment]
Depends. If one is willing to assume correctness of the model (e.g., because its correctness is established by other means, like for example model checking of interactive theorem proving), then the program is considered correct when verification passes with only the `--check-history` flag.

This is a realistic use case. So both flags (`--check-history` and `--check-defined`) are needed, but they shouldn't be used at the same time.

However, if verification fails with `--check-history`, then the program is definitely incorrect.

**Comment by bobismijnnaam** [comment]
Alright, then we should probably just make it an error when more than one of the --check-* flags is used.

We can work around the testing limitation for now by just duplicating the futures test, but that feels a bit hacky. We can also implement option sets for the tests, i.e. allow the tests to specify multiple sets of options the file should be tested with. @niomaster Do you think this would be difficult? Or unneccessary?

**Comment by niomaster** [comment]
I believe option sets already work for other "test options", so it shouldn't be too hard to implement.

**Comment by bobismijnnaam** [comment]
I want to put this back on the radar. At least for a few tests, the --check-defined flag does not work properly anymore, where I would expect it to. For example, the counteradd_2.pvl and unequalcounting.pvl files I would expect to verify with --check-defined. The first does not properly encode a member function put on the future class and results in an internal error, and for the second one the contract is not correct.

To resolve this, first the bug & contract for these two and possibly other tests need to be fixed.

After that, I think we should refactor the future code to always check for both "--check-history" and "--check-defined", and add a flag/syntax to the future class that turns "--check-defined" off when correctness is established externally, to avoid catching bugs like these late in the future.
