### ISSUE TITLE
Example demo/demo4.pvl is broken because of current dependencies

### ISSUE THREAD

**Issue by bobismijnnaam** [utwente-fmt/vercors#375]
`demo/demo4.pvl` currently does not verify in vercors 5dfa950cd8e1e7c457d45c24dd4819ca64de1a53. In vscode (don't know how to see the version?) it verifies most of the file, except for "constraining" blocks. I think this is because a certain axiom emitted by vercors is not applied by viper/z3 (namely, an axiom defining equality between a process and its definition). The (presumably older) version used by vscode seems to have no trouble using the axiom. I think we can either downgrade or figure out a way to tell viper/z3 to use the axiom somehow.

**Comment by Sophietje** [comment]
If you are looking for the version of viper that you're using in Visual
Studio Code, try going to the menu "View"->"Extensions". This should then
show a list of enabled extensions and their version.

**Comment by niomaster** [comment]
I'm not in favor of downgrading z3 in general, because it is fragile in the long term. Maybe we could consider tracking the z3 version of viper, or maybe we should have a flag that tells VerCors to use the viper backend in the vscode plugin, such that the output at least matches the vscode output to facilitate debugging.

**Comment by niomaster** [comment]
By "the z3 version of viper" I mean the minimum that they require, or the vscode version.

**Comment by wytseoortwijn** [comment]
Which version are you using?

**Comment by niomaster** [comment]
4.8.5, currently. This was just the newest version the last time we updated.

**Comment by wytseoortwijn** [comment]
Hmmm, does it work with 4.8.6? That one should be fairly stable, at least with the current version of Viper. Downgrading doesn't sound very attractive indeed.

**Comment by wytseoortwijn** [comment]
> I think this is because a certain axiom emitted by vercors is not applied by viper/z3

Perhaps this is a problem of triggering? Might adding (different) triggers solve this?

**Comment by niomaster** [comment]
I think the axiom in question was an equality at the top (i.e. not a quantifier), I don't think you can apply triggers to that?

**Comment by wytseoortwijn** [comment]
Aah, I thought it was one of the generated ones:

```
axiom method_Future_OG_def_1 {
  p_merge(p_method_Future_incr(), p_method_Future_incr()) == p_method_Future_OG()
}

axiom method_Future_OG_def_2 {
  (forall p: Process :: { p_seq(p, p_method_Future_OG()) } p_seq(p, p_method_Future_OG()) == p_seq(p, p_seq(p_method_Future_OG(), p_empty())))
}
```

These indeed have no trigger, so it might very well be that they aren't instantiated.

**Comment by bobismijnnaam** [comment]
I also thought it was OG_def_1. Unsure how to add triggers to this.

**Comment by wytseoortwijn** [comment]
Hmmm, but there are other axioms that don't have triggers. For example, the following three might potentially cause matching loops:

```
axiom empty_1L {
  (forall p: Process :: p_merge(p_empty(), p) == p)
}

axiom empty_2L {
  (forall p: Process :: p_seq(p_empty(), p) == p)
}

axiom empty_2R {
  (forall p: Process :: p_seq(p, p_empty()) == p)
}
```

By "currently does not verify in vercors", do you mean that it fails, or doesn't terminate? If it doesn't terminate, one could try to add triggers to these axioms to see if it makes any difference.

**Comment by wytseoortwijn** [comment]
Well, regardless of whether this causes `demo4.pvl` to be broken or not, I think these three axioms should have triggers.

**Comment by bobismijnnaam** [comment]
> By "currently does not verify in vercors", do you mean that it fails, or doesn't terminate? If it doesn't terminate, one could try to add triggers to these axioms to see if it makes any difference.

I mean that vercors says "Assertion failed at" or "cannot prove method contract at" (sorry, should've included a printout of vercors output). It happens at the line where the future is split.
