### ISSUE TITLE
Vercors should not succeed when then is used without yields

### ISSUE THREAD

**Issue by bobismijnnaam** [utwente-fmt/vercors#380]
I have the following snippet:

```
class MyClass {
  given int x;
  void bar();

  void foo() {
    int y = 3;
    bar() with { x = 4; } then { y = y; }; 
    assert y == 3;
  }
}
```

I would expect an error, since `bar()` does not have a `yields` clause of any kind. However Vercors succeeds without complaining. In the generated silver code the `then` clause (which corresponds to an assignment if I understand correctly) is absent:

```
method method_MyClass_foo(diz: Ref, current_thread_id: Int, globals: Ref)
  requires diz != null
  requires 0 <= current_thread_id
{
  var y__1: Int
  y__1 := 3
  method_MyClass_bar(diz, current_thread_id, globals, 4)
  // assert
  assert y__1 == 3
}
```

This is probably a scoping error, since I defined my own `y` on the first line of `foo`. Nevertheless, I think Vercors should either warn me or error that `bar` has no `yields` and that it doesn't influence the `y` variable at all. Erroring is the most proper response here I think.

**Comment by niomaster** [comment]
with/then is now different from supplying arguments with given/yields, so this is solved.
