### ISSUE TITLE
The order of type parameters in a self-defined domain is not retained

### ISSUE THREAD

**Issue by OmerSakar** [utwente-fmt/vercors#381]
Suppose we have a domain in prelude.sil:

```
domain MyDomain[F,S] {
    function myFunc(): MyDomain[F,S]
}
```

The SilverClassReduction reads prelude.sil and adds this domain to the COL AST as an AxiomaticDataType. The order of the type variables here is still maintained (for both the domain and the return type of the function). When the program is mapped to Silver, the domain still has type variables [F,S], but the function has a return type with type vars [S,F].

I believe the problem lies in SilverTypeMap and SilverTypeFactory. For the case above, the method `domain_type` in SilverTypeMap is called (https://github.com/utwente-fmt/vercors/blob/dev/src/main/java/vct/silver/SilverTypeMap.java#L53-L64). This method gets a map of Strings to some type T. For the case above it is filled with the entries ("F" -> the instantiated type) and  ("S" -> the instantiated type). The instantiated type does not matter here. 

Next, a domain type is created using SilverTypeFactory (https://github.com/utwente-fmt/vercors/blob/dev/viper/src/main/scala/viper/api/SilverTypeFactory.scala#L25-L31). Here lies the real issue. In the first line of this method, the key set of the map (we created above) is taken and converted to a sequence. So we have a sequence of Strings (for the example above ["S", "F"]). There is nothing that guarantees the order of this sequence. This results in an assertion error in Viper.

I believe that this issue was never found since there are no other domains using more than one type variable. The workaround is naming your type variables to be in a specific order, however, nothing guarantees that the order won't change from Java version to Java version.

I have looked at a possible solution which is instead of using a Map (i.e. no order retained) we could use a list of tuples.

**Comment by niomaster** [comment]
Or maybe we could use a `scala.collection.immutable.ListMap` (https://www.scala-lang.org/api/current/scala/collection/immutable/ListMap.html). I'm not convinced that we really need a map, though? Is there something we check using the typevar assignments?

**Comment by OmerSakar** [comment]
The map is used by the Scala class DomainType (in the Silver project). I looked at the usages and implementation of this method. For Silicon, we do not check anything. For the VerCorsTypeFactory, a ClassType is created and I do not know if something is checked on that ClassType.

**Comment by OmerSakar** [comment]
Instead of using a Scala ListMap (which is difficult to convert from and to a Java Map), the solution uses a LinkedHashMap which functions the same (i.e. the keys are in the order of insertion).

Basically, everywhere where a HashMap was used, a LinkedHashMap is used.

**Comment by OmerSakar** [comment]
I have assigned myself to this issue since I already fixed it in one of my branches (see ed8857b17a20b54d477f5705f11004e12b657038). This issue will be closed when this branch is merged back in dev.

**Comment by niomaster** [comment]
Is this branch still due to be merged? (No rush, just checking that the fix does not get lost)

**Comment by OmerSakar** [comment]
Yes, I will mention this issue in the PR when it is made.
