### ISSUE TITLE
Futures might use non-supported Viper constructs

### ISSUE THREAD

**Issue by bobismijnnaam** [utwente-fmt/vercors#383]
When asked to check my code that uses futures, Vercors emits Viper code that is no longer supported (https://github.com/viperproject/silicon/issues/35). For example, when the following snippet: https://gist.github.com/bobismijnnaam/322c28f78400b520187ee06844d56ccf is checked using `vct --silicon --check-history monotonic_bool.pvl --encoded temp.sil`, Vercors dev currently emits silver that uses a `constraining` block and a `fresh` statement as can be seen in the `temp.sil` file. Other examples still work (specifically `examples/demo/demo4.pvl`), so it might be that this bug is only triggered when faulty future code (such as my snippet, which is syntactically correct but semantically dubious) is given. However instead Vercors should give a nice error if that happens.

The `fresh` statement we can work around (as described here: https://bitbucket.org/viperproject/silver/issues/87/remove-fresh-statement). I haven't found any discussion about `constraining` yet so I'm not sure how to fix that, but there probably is a way for that as well. Possibly some `inhale`/`exhale` can be designed for futures to replace `constraining`?

It would also be nice to know why these constructs are/were necessary, as this is not clear from the code. (I haven't looked at it thoroughly but it seems to "just" emit these statements without much comment or reason). Maybe @wytseoortwijn knows more?

As a last option, we can also downgrade all the viper components. But then we will be stuck on a final version...

EDIT: From Malte Schwerhoff's PhD thesis ([link here](https://bitbucket.org/viperproject/silicon/src/default/)) it seems that `constraining` indicates a value for the argument must be found such that whenever it is used, it always leaves some permission for the scope outside. Which more or less means that it's a nice way to encode read permissions without specifying concrete permissions, if I understand it correctly. Vercors uses it in a very limited way, so I think we can just replace the use of `constraining` with an `inhale`/`exhale` pair that leaves some permission for the outside scope (i.e. `inhale f != none && g != none && f < g` or something). This would probably fix my example, but I'm unsure if it works for bigger futures (or histories?) examples.

EDIT 2: It seems this is only triggered when the `accesible` keyword appears in one of the process contracts. Which seems logical, as it concerns read only permissions. Using `modifies` avoids this bug but probably means something different in terms of checking the histories.

EDIT 3: The following issue shows a nice use of constraining: https://github.com/viperproject/silicon/issues/30 It does seem like a feature hard to implement in the front end, but maybe since actions are pretty narrowly defined it can be worked around.

**Comment by mschwerhoff** [comment]
@bobismijnnaam Quite a while ago, Viper team member @vakaras worked on a front-end encoding of the `constraining` feature. If you're interested, I'm sure he wouldn't mind hearing from you.

**Comment by bobismijnnaam** [comment]
@mschwerhoff Thank you for the heads up! I will get in touch with him.
