### ISSUE TITLE
Using methods as top-level entities gives NullPointerException

### ISSUE THREAD

**Issue by bobismijnnaam** [utwente-fmt/vercors#385]
The following snippet:

```
  given frac f;
  context_everywhere 0 < f && f < 1;
  context_everywhere xs != null;
  context_everywhere t > 0;
  context (\forall* int i; i >= 0 && i < xs.length; Perm(xs[i], f));
  void parRead(int[] xs, int t) {
    par parRead(int tid=0..t)
    context (\forall* int i; i >= 0 && i < xs.length; Perm(xs[i], f\t));
    {
      //some Code
    }
  }
```

(from Dre's issue) gives a NullPointerException within the `sat_check` pass. This is logical, because that pass assumes every method is in a class. Funnily enough, the following snippet:

```
int foo() {}
```

gives a NullPointerException directly after the parsing pass. Ideally (in both cases) Vercors would give a friendly error saying top-level entities besides classes are not supported, since that is the assumption most passes seem to make. Or if that is not the case, the `sat_check` and pass after parsing should be accomodated to this.

**Comment by niomaster** [comment]
This is already implemented in the new parser, so let's not fix this in the old parser.
