### ISSUE TITLE
Reassignment of arguments

### ISSUE THREAD

**Issue by wytseoortwijn** [utwente-fmt/vercors#393]
Consider the following VerCors code snippet:
```java
class Test {
  void test(int n) {
    n = 2;
  }
}
```

The following Viper code is generated for it:
```
method method_Test_test__Integer(diz: Ref, current_thread_id: Int, globals: Ref, n: Int)
  requires diz != null
  requires 0 <= current_thread_id
{
  n := 2
}
```

VerCors is able to verify this, whereas Viper isn't (directly). When I give this to Viper in VScode, it tells me that "Consistency error: n := 2 is a reassignment of formal argument n. (test.vpr@5.3)". Does VerCors call Viper in some particular way to prevent Viper from failing?

I think that, whatever VerCors does here, it should change. The right way of handling this reassignment for VerCors is making a new local variable that is written to instead of `n`, like this:
```
method method_Test_test__Integer(diz: Ref, current_thread_id: Int, globals: Ref, __n: Int)
  requires diz != null
  requires 0 <= current_thread_id
{
  var n: Int := __n
  n := 2
}
```

**Comment by niomaster** [comment]
If we apply the workaround you suggest we should consider the behavior of `\old` expressions, e.g.:

```
ensures n == \old(n);
void test(int n) {
  n = n + 1;
}
```

Actually I just tried this to make sure and it seems it currently passes...

**Comment by niomaster** [comment]
The checks we need from viper are defined in `viper.silver.frontend.Frontend`, which does consistency checks etc., after which one of the verifiers is called. We instantiate one of the verifiers directly, so the consistency check is never performed. 

Not really sure what a good entry point is then, because `Frontend` also does things like file reading + parsing, which we already have a rewriter for.

**Comment by wytseoortwijn** [comment]
That code snippet should indeed pass.

I don't think VerCors should ignore that Viper in principle doesn't allow reassigning arguments. It could very well be that this introduces unsoundnesses under the hood, for example since Viper generates proof obligations under the assumption that arguments are not reassigned.

And even if everything does go right now, it is quite possible that certainly things go wrong after an update of the Viper backend.

**Comment by niomaster** [comment]
I think you misunderstood me. Indeed we should expect the snippet to pass in viper, but I meant it in the context of VerCors. In that case I think it should not pass (simply because our frontend languages allow argument reassignment), but the example currently does pass. I am in agreement with you that we indeed should not just hope for the best and pass an invalid program with argument reassignment to viper.

My point was more that we should consider `old` expressions in how we rewrite cases with argument reassignment, e.g. if we blindly rewrite the above (Vercors) example to something like this (Viper):

```
ensures n == old(n)
method test(n: Int) {
  var n': Int // generated
  n' := n // generated
  n' := n' + 1
} 
```

It would report pass. We would want the `n` in `ensures n == old(n)` to refer to `n'` instead, in which case the example would (correctly, IMO) fail.

**Comment by wytseoortwijn** [comment]
I am not convinced that it should pass in the context of VerCors. Any changes to `n` should not be observable outside the scope of the method body (unless it is call-by-reference), and therefore also not by `test`'s contract.

Suppose that one would change the semantics of `old` so that the following verifies:
```
ensures n == \old(n) + 1;
void test(int n) {
  n = n + 1;
}
```

Then that leads to strange situations. Would the following then also verify?
```
void test2() {
  int n = 10;
  test(n);
  test(n);
  assert n == 12;
}
```

**Comment by bobismijnnaam** [comment]
IMP2 only allows referencing formal parameters in the postcondition if they are wrapped in an `\old` function. Might be a bit drastic/verbose but does make very clear what is actually happening.

**Comment by wytseoortwijn** [comment]
@bobismijnnaam I didn't entirely get that, could you perhaps clarify it a bit further?

**Comment by bobismijnnaam** [comment]
IMP2 allows:

```
ensures \result == \old(n) + 3;
int foo(int n);
```

But not:

```
ensures \result == n + 3;
int foo(int n);
```

Not that it matters too much, since IMP2 also doesn't allow assigning to formal parameters anyway if I recall correctly. But the contract does clearly signify the result is 3 more than `n` at the _beginning_ of the function, and not 3 more than `n` at the end.

**Comment by wytseoortwijn** [comment]
Aah, I see what you mean now. That's indeed a bit drastic.

I don't really like that, since wrapping formal parameters in `\old(..)` like that would imply that there are also "new" values for these parameters, which, from the perspective of the function contract, is not true (only from the perspective of the function _body_ it is true, but that's a different thing).

**Comment by bobismijnnaam** [comment]
JML converts each use of a formal parameter `x` in the postcondition (or signals clause) into `\old(x)` (http://www.eecs.ucf.edu/~leavens/JML/jmlrefman/jmlrefman_9.html#SEC111).

Interestingly, if you apply that rule in the following program:

```
class MyClass {
  boolean pick();

  int x;

  requires Perm(mc.x, 1);
  ensures Perm(\old(mc).x, 1) ** \old(mc).x == 3;
  void bar2(MyClass mc) {
    boolean b = pick();
    if (b) {
      mc = new MyClass();
    }
    mc.x = 3;
  }
}
```

Vercors succeeds, which I wouldn't agree with. Maybe this triggers some unsoundness in Viper? Seems like a bug in any case.

**Comment by wytseoortwijn** [comment]
This should fail indeed. I think the reason that this succeeds but shouldn't, is exactly the problem of reassigning arguments! If I take the Viper output and make a new local variable for `mc` (as in the first comment), I get a verification failure.

Regarding the first remark: also in JML users are not forced to write `\old` while referring to input parameters in postconditions. They could, it's not technically wrong (VerCors should also support it still), but then for example `\old(mc)` would be the same as `mc`.

**Comment by niomaster** [comment]
Yes, regardless of which view we take the program we deliver to viper should pass the consistency check we currently omit.

**Comment by wytseoortwijn** [comment]
This issue also causes unsoundnesses in combination with e.g. parallel blocks (@Safari1991 has an example of one). I think this is quite a serious issue.

**Comment by niomaster** [comment]
I've started a build that does the consistency checks and aborts when there is an error here: https://travis-ci.org/utwente-fmt/vercors/builds/652635598

(In case someone missed it, you can click "Output from case..." in the build log of jobs 1 through 5 to view the output of a failed case, which for this build includes the consistency error)

**Comment by niomaster** [comment]
7 failures in total, of which 2 are due to argument reassignment. There's also a couple that fail due to "Duplicate identifier", which also sounds very bad... I'll investigate them all a bit more later.

**Comment by niomaster** [comment]
The FinalizeArguments pass implements exactly what we need, but just isn't enabled for the silicon backend.
