### ISSUE TITLE
Better translation of `return`s

### ISSUE THREAD

**Issue by wytseoortwijn** [utwente-fmt/vercors#397]
Consider the following code snippet:
```java
class Cell {
  int val;
  
  context Perm(c.val, write);
  ensures c.val == 10;
  void update(Cell c) {
    c.val = 10;
    return;
    c.val = 20;
  }
}
```

VerCors generates the following Viper code for the `update` method:
```
method method_Cell_update__Cell(diz: Ref, current_thread_id: Int, globals: Ref, c: Ref)
  requires diz != null
  requires 0 <= current_thread_id
  requires acc(c.field_Cell_val, write)
  ensures acc(c.field_Cell_val, write)
  ensures c.field_Cell_val == 10
{
  c.field_Cell_val := 10
  // assert
  assert acc(c.field_Cell_val, write) && c.field_Cell_val == 10
  inhale false
  c.field_Cell_val := 20
}
```

This encoding of `return` is a bit messy and can be improved upon. Would be a lot better to translate it to:
```
method method_Cell_update__Cell(diz: Ref, current_thread_id: Int, globals: Ref, c: Ref)
  requires diz != null
  requires 0 <= current_thread_id
  requires acc(c.field_Cell_val, write)
  ensures acc(c.field_Cell_val, write)
  ensures c.field_Cell_val == 10
{
  c.field_Cell_val := 10
  goto returnlabel
  c.field_Cell_val := 20
  label returnlabel
}
```

If after the `return` there is still a lot of (unreachable) code for example, then this would probably improve the situation.

**Comment by bobismijnnaam** [comment]
I am planning on reworking this while implementing exceptions, as returning early is another form of abrupt termination. But that is going to take a bit longer for now.

**Comment by niomaster** [comment]
From Wytse's description I gather that this would mostly be a performance improvement, so I think it's okay to wait for Bob's solution rather than implementing something else first.

**Comment by bobismijnnaam** [comment]
This is now implemented on dev.
