### ISSUE TITLE
Cannot create language specific passes over multiple input files

### ISSUE THREAD

**Issue by bobismijnnaam** [utwente-fmt/vercors#402]
Currently Vercors doesn't easily support language specific passes over multiple input files. There are not many passes where this is really needed, however for example for java type resolution it would be good if all classes were already parsed. Currently the java_resolve pass is also applied to PVL programs, since that is the current (only) way of applying a pass to all input files. The pvl-encode pass is another example of this (currently worked around by scanning for PVL specific constructs).

Somewhat related to this: currently Vercors also accepts input files of different languages (i.e. a c file + a java file) at the same time. Maybe we can fix/formalize which combinations of languages Vercors accepts.

**Comment by niomaster** [comment]
VerCors still accepts multiple input languages at the same time, but the fact that they cannot communicate significantly is well-defined: e.g. c/java names cannot refer to java/c variables by virtue of the resolver, but specification constructs across languages do work. I think it's fine like that.
