### ISSUE TITLE
\memberof range expressions lead to unbalanced parentheses

### ISSUE THREAD

**Issue by niomaster** [utwente-fmt/vercors#403]
ranges in the simplification rules are written close to the regular math syntax, `[a..b)` for `a`-inclusive, `b`-exclusive. I think we should change this to a parentheses-balanced syntax, some alternatives from other languages:

 - `(a..b)` (exclusive) and `(a..=b)` (inclusive) from Rust
 - `[a..b]` (inclusive) and `[a..<b]` (exclusive) from Isabelle

I propose `{a..<b}` and `{a..<=b}`, as that's most explicit and our sequence notation is `{}`.

**Comment by bobismijnnaam** [comment]
Good idea! I think the Rust one is preferable, as exclusive as default seems useful, but either one is a good choice.

No plans for the lower bound? (not saying that should be possible - just wondering. Not sure if even Isabelle has something like that)

**Comment by niomaster** [comment]
Personally I don't think I've come across a situation in which a left-exclusive range would be clearer than `+1`, so I think it's okay to leave that out.

**Comment by niomaster** [comment]
I'll make a PR for `{a..b}` and `{a..=b}` and see if anyone complains :D

**Comment by raulmonti** [comment]
I do not like {} very much for a range, but it may be that I am more used to finding () for ranges. Even though {} are used for sequence notations, I think that what you expect to find inside them are elements of the sequence instead of indexes? Am I wrong? An other option is to have \sum to take two integers instead of a range as first argument.

**Comment by niomaster** [comment]
I'm not sure what you mean by elements of the sequence vs. indices, but a notation like `{0..4}` is now supposed to be exactly `seq<int> { 0, 1, 2, 3 }`. The range notation is not only used in `\sum` statements, but also in the normalization of `\forall` expressions. It's extensively used in the simplification rules. Hope that clears it up a bit!
