### ISSUE TITLE
Negative array sizes

### ISSUE THREAD

**Issue by bobismijnnaam** [utwente-fmt/vercors#416]
Currrently VerCors allows negative array sizes, both in the Java and PVL frontend. Java throws an exception in this case, so at least in the java frontend it should be an error (unless we want to allow it if the function declares the proper `throws` clause - which I am currently not planning to allow, unless someone objects). For PVL I think it would be good to forbid it as well. It can probably be encoded straightforwardly by emitting an assert before array creation, asserting that it should be `>= 0`. Any objections? (Unless this is already implemented - then it must be currently broken)

For reference, I used the following program:

```
public class ArrayBounds {
    public void foo() {
        int[] arr = new int[-1];
    }
}
```

Both `ArrayBounds.java` and `ArrayBounds.java --lang=pvl` verify with the current dev branch.

**Comment by niomaster** [comment]
I think a good solution would be to have `RewriteArrayRef.arrayConstructorContract` append requirements for the dimension sizes

**Comment by ArmborstL** [comment]
Note that using a negative array length makes the knowledge base inconsistent, and `assert false` verifies successfully.

**Comment by niomaster** [comment]
Let's solve this in tandem with https://github.com/utwente-fmt/vercors/pull/284
