### ISSUE TITLE
"Precondition unsatisfiable" error occurs when postcondition fails

### ISSUE THREAD

**Issue by bobismijnnaam** [utwente-fmt/vercors#417]
Sometimes VerCors reports that the precondition cannot be satisfied even when it can be satisfied. I think this happens when also the postcondition is not satisfied in the actual body of the method. Unfortunately I don't have a MWE, since I've only seen it happen in big specifications (& not on my laptop & not very often in general). I think it can be fixed by ensuring that the contract for the sat check produced by SatCheckRewriter.java only contains `requires` clauses, and no `ensures` clauses. The `ensures` clause is not needed to check satisfiability of the precondition so it should be removed anyway. If we happen upon a MWE at some point we can maybe investigate and try if this fix works.

Since this happens rarely we don't have to do something immediately, but for the time being I wanted to document that this might be a known problem.

**Comment by niomaster** [comment]
Unsatisfiable preconditions are checked by the absence of an error, yes? So you say you have a case that (sometimes) reports precondition unsatisfiable, indicating that there is an error missing from viper where you would expect one?

**Comment by bobismijnnaam** [comment]
Yes, that sounds right. Maybe in some situations if the post conditions become complex enough viper first checks the postcondition and then the statements within, causing the `assert false` not to trigger. I've also seen this happen a few times when lots of branching (i.e. gotos) are involved. Then this can also be solved by adding an `inhale false` after the `assert`, which sounds right, although I feel like removing the post condition is cleaner...?
