### ISSUE TITLE
Use silicon as a default back-end

### ISSUE THREAD

**Issue by Sophietje** [utwente-fmt/vercors#424]
Currently when using VerCors, the user always needs to specify which back-end to use. However, I believe at this point we always use silicon (which is also the only supported back-end?). So I think it'd be nice to use silicon as a default back-end when no back-end has been specified.

**Comment by niomaster** [comment]
frontend because it's a flag / interface issue :)

**Comment by niomaster** [comment]
implemented via flags refactor.
