### ISSUE TITLE
Java multi-line specification - show a warning

### ISSUE THREAD

**Issue by Sophietje** [utwente-fmt/vercors#434]
When writing a specification in a Java file, the user should use
```
/*@
   _spec here_
*/
```

If the user instead uses 
```
/*
@ _spec_
@ _spec_
*/
```
then the specification is not checked, which is VERY UNCLEAR. I want some kind of warning or error whenever such a comment exists in the program, the user is made aware that this is not verified!

**Comment by niomaster** [comment]
I propose we close this via #437, because the new parser enforces that an `@` symbol is followed by a valid contract (ignoring further `@` symbols at the start of a line)

**Comment by niomaster** [comment]
To be clear, an `@` symbol in any place must be followed by a contract

**Comment by Sophietje** [comment]
Wouldn't this clash with JavaDoc?

Sophie

**Comment by niomaster** [comment]
Yes, very observant :). So for further `@` symbols we now require that they are preceded by a newline (so they don't clash with the predicate family syntax), I think a good idea might be to require the same for the first `@`. In normal javadoc you instead start the line with `* @param` or so, so then it would not clash anymore.

**Comment by bobismijnnaam** [comment]
> I propose we close this via #437

How would this solve Sophie's issue? I thought in Sophie's example the new parser would just ignore the comment as well. Since the comment does not start with a ```/*@``` it is just plain ignored.

Or is it the case that the new parser expects a contract after ```@```, even if the comment itself **did not start with an ```//@``` or ```/*@```?** If this is the case we're not following the JML spec (which is okay, I guess, but should probably be noted explicitly then). 

Or am I misunderstanding this whole issue big time? 😅

**Comment by niomaster** [comment]
It is indeed the case that we expect a contract after `@` even if the comment does not (immediately) start with `@`.

**Comment by bobismijnnaam** [comment]
Interesting, so now you can put comments in your specifications without starting a new comment?

```
/*
 First we specify orderedness:
 @ requires ordered(this)

 Then we ensure atomicity:
 @ ensures atomic(this)

 */
```

If that's the case then I guess VerCors supports literate specification! :D

**Comment by niomaster** [comment]
Haha, almost! But not quite: any lines following the first `@` at the start of a line are part of the contract, so in this case there would be a parse error on "Then we ensure atomicity."
