### ISSUE TITLE
Using lock in constructor is unsound

### ISSUE THREAD

**Issue by bobismijnnaam** [utwente-fmt/vercors#438]
VerCors passes the following:

```
class C {
  int x;
  resource lock_invariant() = Perm(x, write);

  C(int y) {
    lock this;
    unlock this;
    assert false; // Oops, shouldn't have allowed lock in constructor, obviously
  }

  C() {
    bad();
    assert false; // Oops, shouldn't have allowed calling bad because...?
  }

  context Perm(x, write);
  ensures 2 == 3;
  void bad() {
    lock this;
    unlock this;
  }
}
```

One easy fix is to not allow locking in the constructor. However that's undesirable for two reasons:

1. In e.g. Java locking on this is allowed in the constructor
2. Calling other functions can then still break it, so it doesn't work anyway

I discussed a bit with Pieter already, and we came up with at least two solutions:

1. Have ```lock``` require some sort of ```can_lock(this)``` predicate, that is only supplied after the constructor is finished. While effective, requires can_lock to be added to every contract, and also does not allow the user to use lock inside the constructor (which would be nice to keep for Java)
    - Maybe in those cases users could force the lock invariant to be established with extra syntax. But then there is still the extra annotation overhead.
2. Encode the lock invariant along the lines of ```initialized ==> lock_invariant()```, and then only setting the initialized var at the end of the constructor. However the concrete implementation for this isn't immediately clear to me (how handle permissions for initialized?), and then it starts to look a lot like some kind of class invariant in disguise...

I guess a temporary patch would be disallowing/warning about lock in constructors, and also warning for this caveat when methods are called in the constructor.

**Comment by bobismijnnaam** [comment]
In the locking paper from clement (maybe not the right one but related: Reasoning about Java’s Reentrant Locks, 2008) it is required that lock invariants are initialized before they can be locked. After some discussion in the meeting we decided that the annotation overhead for initialized is probably a bit much, so vercors should only warn/fail if lock statements are encountered in the constructor. This can possibly be combined by having a commit statement that forces initialization of the lock invariant, and therefore safely allows locking in the constructor if the commit statement is used first.

**Comment by niomaster** [comment]
I want to implement this via obligations, so kind of an "inverted" `can_lock` (say `should_commit`). Via `forperm` we can check at all modularity boundaries that the resource is not leaked:

```
forperm obj: Ref [should_commit(obj)] :: false
```

Then when locking we should `assert perm(should_commit(obj)) == none`. We should check syntactically that obligations do not occur in predicates or magic wands.

**Comment by niomaster** [comment]
This does not quite work with threads, since you can transfer + hide the commit obligation in one thread, while witnessing its absence in another thread. For now, we just went with the boolean predicate solution.
