### ISSUE TITLE
Java logical xor support

### ISSUE THREAD

**Issue by bobismijnnaam** [utwente-fmt/vercors#442]
VerCors does not support logical xor for Java. Example program:
```
class C {
  boolean foo() {
    return false ^ true;
  }
}
```
Output:
```
$ vct-dev --silicon temp.java
[warning] (class vct.col.util.FeatureScanner): at file temp.java from line 1 column 1 until line 5 column 1: detected inheritance
At file temp.java from line 3 column 12 until line 3 column 23: Types of left and right-hand side argument are different (Boolean/Boolean).
The final verdict is Error
```
(JLS reference: https://docs.oracle.com/javase/specs/jls/se7/html/jls-15.html#jls-15.22.2)

**Comment by niomaster** [comment]
So if I read it correctly, `&`, `|` and `^` are not only bitwise operators, but also boolean operators when the lhs&rhs are both boolean. This means there is no low-precedence operator, because there is no logical-only xor operator (such as `^^`)
