### ISSUE TITLE
Reduce release size

### ISSUE THREAD

**Issue by niomaster** [utwente-fmt/vercors#447]
There's some really low-hanging fruit to reduce the size of Vercors releases. In particular, we still include dafny/boogie/chalice even though we don't support them anymore, and builds of z3 for all platforms are included for every platform.

**Comment by Sophietje** [comment]
Dafny/Boogie/Chalice are no longer included as of #586

**Comment by niomaster** [comment]
No, mac binaries are in Mach-O format, rather than ELF:

```
$ file src/main/universal/res/deps/z3/4.8.6/Darwin/x86_64/bin/z3 
src/main/universal/res/deps/z3/4.8.6/Darwin/x86_64/bin/z3: Mach-O 64-bit x86_64 executable, flags:<NOUNDEFS|DYLDLINK|TWOLEVEL|WEAK_DEFINES|BINDS_TO_WEAK|PIE>

$ file src/main/universal/res/deps/z3/4.8.6/Linux/x86_64/bin/z3 
src/main/universal/res/deps/z3/4.8.6/Linux/x86_64/bin/z3: ELF 64-bit LSB executable, x86-64, version 1 (GNU/Linux), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, for GNU/Linux 2.6.32, BuildID[sha1]=18cc4bfa31c02cab4707df7bb6783c89b85fadac, not stripped

```

**Comment by Sophietje** [comment]
> > we still include dafny/boogie/chalice even though we don't support them anymore
> 
> Carbon works again so please don't delete boogie :) But it can be a lot improved, since now we include three separate boogies, but I think most of that can be deduplicated into one. I also have a gut feeling the mac z3 runs on linux z3 as well, but the executables differ quite a bit so I'm not too sure about that...

I should've been more specific, the old Boogie backend has been deleted

**Comment by bobismijnnaam** [comment]
This issue can maybe be accomplished with sbt native packager's submodules: https://sbt-native-packager.readthedocs.io/en/latest/recipes/package_configuration.html#sbt-sub-modules

**Comment by niomaster** [comment]
The low hanging fruit has been done.
