### ISSUE TITLE
jspec simplification pass & generics

### ISSUE THREAD

**Issue by bobismijnnaam** [utwente-fmt/vercors#452]
Currently, the jspec simplification pass does not support generics. This is not a practical problem, but it prevents simplification rules that would work generically over multiple datatypes. For example, the following rule squashes forall* quantified read permissions:
```
  axiom collapse_read_perm {
    (\forall* int tid; (tid \memberof {e1 .. e2}); Perm((bs1!tid), read))
    ==
    (e1 < e2) ==> Perm(bs1, read)
  }
```
In my example, I defined `bs1` as a `boolean[]`, so this rule can only simplify read permissions for fields of type `boolean[]`. To make this rule work for integer fields, a variant needs to be added that uses `e3` instead of `bs1`, and similarly for boolean, floats, etc. Right now the workaround would be to add the rule for the types you need, but this is not an ideal situation.

This can be solved in at least two ways:
- Add a "wildcard type" with no constraints that matches any type. This would probably be the most straightforward solution, but it also kind of defeats the purpose of type-checking these rules to begin with.
- Piggy-back on top of the generics implementation that vercors will have for the java front-end at some point in the future, and integrate that in the rewrite system.

I think it is not guaranteed that the generics support will easily integrate with the rewrite system, so it could be useful to investigate both approaches.

**Comment by niomaster** [comment]
A wildcard type does not necessarily have to break type checking. You might have a rule that shifts array indices `a[i+1] -> a[i]`. Then you could declare `a` as type `?[]` or so. The type checking then is of course only as strict as you write it, but that is already the case now anyway.

**Comment by bobismijnnaam** [comment]
I think it would allow you to introduce subtle errors though if you're not careful. For example, should the following rule be allowed?

```
WildcardType w1, w2;
axiom int_to_bool {
w1 + w2 == w1 || w2
}

**Comment by niomaster** [comment]
I think fixing the type and then checking the right-hand side is tantamount to implementing generics though... What about having the `?` type allow no operations? So `?[]` supports indexing, but you can't then do anything with the `?` (except make it the first argument of `Perm` maybe)

**Comment by bobismijnnaam** [comment]
Then we'd basically only implement generics for indexing and usage as a perm argument. That might be a nice restriction to keep it safe.

**Comment by niomaster** [comment]
This is implemented with type-values now, e.g.:

```
axiom starall_star {
  (∀type<any> T, resource r1, resource r2;
    (∀* T t; (r1!t) ** (r2!t)) ==
    ((∀* T t; (r1!t)) ** (∀* T t; (r2!t))))
}
```
