### ISSUE TITLE
Running clang fails if file path contains spaces

### ISSUE THREAD

**Issue by ArmborstL** [utwente-fmt/vercors#475]
When analysing a C file, the parsing with Clang fails if the path of that file contains a space. The path is then split at the space, and a _"no such file or directory"_ error is raised by Clang for the path up to the space, as well as for the path after the space. 
The issue might be resolved by quoting the path, or by using a parameter list for the `exec` call in the ColCParser.

The issue might be platform-dependent, it at least occurs on Windows.

**Comment by niomaster** [comment]
This line https://github.com/utwente-fmt/vercors/blob/86c06a0fe213348403acb654c96fd14af559ae70/parsers/src/main/java/vct/parsers/ColCParser.java#L38 should not use `Runtime.exec`, but for example a `ProcessBuilder` as here: https://github.com/utwente-fmt/vercors/blob/z3-progress/hre/src/main/java/hre/io/NamedPipe.scala#L42
