### ISSUE TITLE
Better reporting if dereferencing field that is null

### ISSUE THREAD

**Issue by ArmborstL** [utwente-fmt/vercors#479]
I called a method `myObj.myMethod();` and VerCors complained that _"CallPreCondition:AssertionFalse"_. The precondition of `myMethod` looked like it was satisfied, though. Looking at the Viper result, it turned out that the generated precondition `diz.myObj != null` might not hold.
I think the error message for generated preconditions should be more verbose, stating what the problem really is. At least for the `null` check, that should hopefully not be too difficult, and a message like _"message invocation on field that may be null"_ would be more useful.

**Comment by bobismijnnaam** [comment]
Just want to leave some useful information in case someone starts working on this: there seems to be a useful mechanism in vercors for generating new origins for generated code such as this. I think an example of this mechanism is located at the method `branching_pass` in `vct.main.Main`. Enabled passes seem to be able to post process over errors received from viper and check if one of their own origin appears. Maybe we can figure out how this works in detail, and then use this mechanism to implement the refining of errors like these. (And then we should also refactor satcheck to use this, see #469)

**Comment by Sophietje** [comment]
An example for reproducing the issue (from #489):
```
class Lock{
	boolean trylock() {
		return false;
	}
}

class Test {
	int L;
	Lock locks[];
	
	/*@
		final thread_local resource lockset(bag<int> S)= Value(L) ** L > 0 ** Perm(locks, write) ** locks != null **
														(\forall* int j; j >= 0 && j < L; Perm(locks[j], write));
	@*/
	
	/*@
		given bag<int> S;
		requires lockset(S);
		requires Value(L) ** L > 0;
    	requires 0 <= lock_id < L;
	@*/
    boolean trylock(int lock_id){
      boolean res;
      //@ unfold lockset(S);
      res=locks[lock_id].trylock();
      /*@ ghost 
        if (res) {
          fold lockset(S+bag<int>{lock_id});
        } else {
          fold lockset(S);
        }
      @*/
      return res;
    }
}
```

**Comment by niomaster** [comment]
You get a more specific error now.
