### ISSUE TITLE
\unfolding breaks Java compilation

### ISSUE THREAD

**Issue by ArmborstL** [utwente-fmt/vercors#485]
Using `\unfolding` in the annotations of Java code results in `javac` complaining that `nfolding` is not a valid unicode, i.e. `\u` is a predefined escape sequence for the Java compiler. Annotated Java code should still be compilable, so an alternative to `\unfolding` is needed.
The proposed solution is capitalisation, i.e. VerCors should allow `\Unfolding` as an alternative spelling. This passes the Java compilation.

**Comment by ArmborstL** [comment]
Looking at the [SpecParser.g4](https://github.com/utwente-fmt/vercors/blob/82106e442581495f6a100a790c8abd8c068baec5/parsers/lib/antlr4/SpecParser.g4#L271), the proposed solution seems to be implemented now.

**Comment by niomaster** [comment]
yes, thanks
