### ISSUE TITLE
"globals" parameter not added if contract calls function that needs it

### ISSUE THREAD

**Issue by ArmborstL** [utwente-fmt/vercors#486]
During the internal transformations, VerCors adds an artificial parameter `globals` to some function definitions. In the PVL example below, it only adds it for `precond`, but not for `myFunction`:
```java
requires arr != null;
requires Perm(arr[0], 1\2);
static pure boolean precond(int[] arr) = true;

requires arr != null;
/// requires Perm(arr[0], 1\2);
requires precond(arr);
static pure boolean myFunction(int[] arr) = true;
```
Since the precondition of `myFunction` calls `precond`, this causes an error: "_Local name globals is undefined_" on the invocation `requires precond(arr);`. 
The reason is that in the `JavaEncoder`, the check `needs_globals` only checks if the pre- and postconditions are boolean, adding `globals` if not. It should also check if the contract calls a function that uses `globals`, like this example does.
Adding the commented out precondition circumvents the problem, as the contract of `myFunction` now is non-boolean, so `myFunction` also gets the `globals` parameter added.

Note that `JavaEncoder` sometimes adds a `globals` parameter without checking `needs_globals`. It should be investigated how the issue relates to those cases. However, since the issue is a _missing_ `globals` parameter, unconditionally adding them will most likely not cause problems.

**Comment by ArmborstL** [comment]
While investigating #569 I realised another case where this occurs: Inline functions. Their contract is irrelevant (and actually mostly ignored by VerCors), because any call to the function is replaced with its body, _before_ we check the correctness of the program via Viper. So a PVL program like this should verify successfully:
```java
    requires Perm(x, write);
    ensures \result == x+1;
    pure int foo();
    
    // requires Perm(y, write);
    pure inline int bar() 
        = foo();


    context Perm(x, write);
    ensures x == \old(x)+1;
    void foobar() {
        x = bar();
    }
```
However, it gives the same error as above, because the contract of `bar` (which is empty) does not require `globals` while `foo` does.
Adding the commented-out line to the contract of `bar` works around the issue and allows the program to verify, even though it refers to `y`, which neither `foo` nor `foobar` have access to.

**Comment by niomaster** [comment]
This all works these days.
