### ISSUE TITLE
Precondition reported to be false when there is no precondition

### ISSUE THREAD

**Issue by Sophietje** [utwente-fmt/vercors#489]
The following code results in a `CallPreCondition: AssertionFalse` which seems weird since there is no precondition for the method `trylock` of the `Lock` class.
```
class Lock{
	boolean trylock() {
		return false;
	}
}

class Test {
	int L;
	Lock locks[];
	
	/*@
		final thread_local resource lockset(bag<int> S)= Value(L) ** L > 0 ** Perm(locks, write) ** locks != null **
														(\forall* int j; j >= 0 && j < L; Perm(locks[j], write));
	@*/
	
	/*@
		given bag<int> S;
		requires lockset(S);
		requires Value(L) ** L > 0;
    	requires 0 <= lock_id < L;
	@*/
    boolean trylock(int lock_id){
      boolean res;
      //@ unfold lockset(S);
      res=locks[lock_id].trylock();
      /*@ ghost 
        if (res) {
          fold lockset(S+bag<int>{lock_id});
        } else {
          fold lockset(S);
        }
      @*/
      return res;
    }
}
```

When the code is translated to Viper, some preconditions are introduced one of them being `diz != null` which cannot be asserted. The problem can be solved by adding `locks[j] != null` in the \\forall-statement in the resource.
However, the error report is very confusing to a VerCors user. Would it be possible to add something like "object might be null" error message?

**Comment by Sophietje** [comment]
Just saw that this is the same issue as #479 , perhaps the example in here can still be useful for testing/debugging when working on this issue.

**Comment by bobismijnnaam** [comment]
The example looks very useful for confirming your and Lukas' problem is fixed. I propose copying over the example to Lukas' issue and closing this one since it seems to be duplicate.
