### ISSUE TITLE
Cannot map constant value class LongValue

### ISSUE THREAD

**Issue by Sophietje** [utwente-fmt/vercors#492]
The following program results in `HREError: cannot map constant value class vct.col.ast.expr.constant.LongValue`:
```java
public class SwapLong {
  long F;
  long G;
  /*@ requires Perm(F,1) ** Perm(G,1);
      ensures Perm(F,1) ** Perm(G,1);
      ensures F == \old(G) && G == \old(F);
   */
  void n()
  {
    long tmp;
    tmp = F;
    F = G;
    G = tmp;
  }
  
  /*@ requires Perm(F,1) ** Perm(G,1);
      ensures Perm(F,1) ** Perm(G,1);
      ensures F == \old(F) && G == \old(G);
   */
  void wrong()
  {
    n();
  }
}
```

Perhaps a missing `LongValue` case in [map(ConstantExpression e)](https://github.com/utwente-fmt/vercors/blob/a54f323e5d360e98aa59f8aeb95e7eba8adba739/viper/src/main/java/viper/api/SilverExpressionMap.java#L61)?

**Comment by niomaster** [comment]
I think rather than pretending we have some distinction between longs and ints we can better just translate long values to IntegerValue's (so unbounded integers) in the parser

**Comment by bobismijnnaam** [comment]
I agree. Maybe we could also emit a warning message whenever a different type than int is used, i.e. "<not int> supported, but no bounds checking for <not int>". Then at least people know we're not doing overflow checking and such once they start types different from ints.

**Comment by niomaster** [comment]
They are now all translated to the same type and constant value node.
