### ISSUE TITLE
Run slow suite at regular interval

### ISSUE THREAD

**Issue by niomaster** [utwente-fmt/vercors#509]
We should use the travis "cron" feature to regularly build the normally excluded suites of examples, so they don't break (I have no idea if they are currently broken, for example). The suites are: slow,medium,problem-fail,skip-travis

I propose we build them monthly. We should only run the examples in the above suites (not the full test suite), which we can distinguish with `TRAVIS_EVENT_TYPE=cron`

**Comment by bobismijnnaam** [comment]
Another idea: maybe in the regular test suite runs, we can include the excluded suites at least for all pre-viper phases. I.e. forall cases in excluded suites, add the flag ```--stop-before silver``` (or maybe ```--no-check```?). That way typing and other properties of the excluded tests are still checked, but we don't have to wait for the viper phase to complete.

**Comment by bobismijnnaam** [comment]
It has been suggested during the meeting that we can also only run the slow tests on the "dev" branch, since commits there are relatively infrequent anyway.

**Comment by bobismijnnaam** [comment]
Related: #487. But, it's probably better to move the slow/medium suite to a new PR, and (finally) close the coverage PR.

**Comment by bobismijnnaam** [comment]
I removed the weekly/slow suite updated code from #487. If needed the changes that I removed can be found at: 776ade43dfa4d08db548899453028575e0753ef0
