### ISSUE TITLE
GPGPU verification

### ISSUE THREAD

**Issue by Safari1991** [utwente-fmt/vercors#513]
There are some issues related to GPGPU verification, in particular OpenCL:

1. "get_global_id(0)" is not supported yet in the tool.
2. It is not possible to define pure functions.
3. The only way to define ghost variables (e.g. sequence) is to define them as "given" in the contract of the kernel. It is not possible to define or update ghost variables inside the kernel.
4. It is not possible to define nested sequences (e.g., seq<seq<int>>) which is very strange.

**Comment by niomaster** [comment]
1. This example passes, so I'm not sure what support is missing?
```#include <opencl.h>

__kernel void test() {
  //@ assert get_global_id(0) == (opencl_gid*opencl_gsize+opencl_lid);
  //@ assert get_local_id(0) == (opencl_lid);
}```

**Comment by niomaster** [comment]
3. Is the classic parse error that `seq<seq<int>>` is tokenized as `seq`, `<`, `seq`, `<`, `int`, `>>`. I suggest to use `seq<seq<int>**space**>` as a workaround for now.

**Comment by niomaster** [comment]
3. I'm not sure what you mean? For example, this passes:

```
#include <opencl.h>

__kernel void test() {
  //@ ghost seq<int> asdf;
  //@ ghost asdf = asdf + asdf;
  //@ assert |asdf| % 2 == 0;
}
```

There definitely is support missing for e.g. explicit sequences (`seq<int>{1,2,3}`) and updating them as in PVL (`asdf[index->value]` and such), so it's probably a good idea to port those into the specification parser from the pvl parser (perhaps @OmerSakar ?). But I don't see how you cannot declare/update them at all.

**Comment by Safari1991** [comment]
What about this example, it does not pass:

#include <opencl.h>
/*@
    requires \pointer_index(a, get_global_id(0), write);
@*/
__kernel void example(int a[]) {
    int tid = get_global_id(0);
    a[tid] = tid;
 
}

**Comment by niomaster** [comment]
Ah okay, though this is not a syntactical issue, but a simplification issue. Should be fixed in 97ca8b9ac1539e0dc9f3db96897d78cec5f6b137

**Comment by Safari1991** [comment]
Okay, what about the second issue? Defining pure functions.

**Comment by niomaster** [comment]
Take a look at #519 :)

**Comment by Safari1991** [comment]
Thanks Pieter!
