### ISSUE TITLE
ContractBuilder uses variable and method for emptiness

### ISSUE THREAD

**Issue by bobismijnnaam** [utwente-fmt/vercors#515]
ContractBuilder uses a boolean to track if it is empty, while this is also captured by `isEmpty()`. Unless there is some benefit to this that I'm missing, this should be refactored to let `isEmpty()` be the single source of truth, as the performance benefit that originally inspired this structure is negligible.

_Originally posted by @niomaster in https://github.com/utwente-fmt/vercors/pull/464#discussion_r464511664_

**Comment by niomaster** [comment]
(not really a bug but certainly a "bug waiting to happen" :fearful:)
