### ISSUE TITLE
NameScanner requires typing information

### ISSUE THREAD

**Issue by niomaster** [utwente-fmt/vercors#518]
NameScanner newly requires names to be type-checked, but I have a case where I want to do (effectively) namescanner(rewrite(node)), which makes that inconvenient. I see there is some internal code that needs the typing information in NameScanner, but I don't quite understand. Maybe you can explain @bobismijnnaam ?

**Comment by bobismijnnaam** [comment]
Type information is needed in one case:

```
x.foo() with { a = x }
```

Specifically, the definition of `foo` is needed to figure out if `a` is a ghost parameter assignment, or a proof step for the method call (useful if the call occurs in a deeply nested expression).

We can make NameScanner more lenient by removing this check, and therefore rely on the check pass to catch errors like this. We could also make this behavior optional so it can be turned off in cases where you know it's safe.

Alternatively, it would be nice if we could restrict usage of NameScanner to cases where we know method invokations with before/after steps do not occur, but that would probably prevent usage of NameScanner too often.

Finally, we could restrict the before/after blocks to only contain simple assignements (i.e. a = x where a is a variable name, and x is a pure expression), but I'm not sure if that would simplify the problem outlined above. Maybe if we disallow using ghost parameters as values in other ghost parameters (i.e. disallow: `with { a = 3; b = a }`).

I think the second or third option would be best for clarity (i.e. make using with/then parameters more restrictive so the checking also becomes simpler), but I'm not sure how freely it is used in the test suite currently.

Was there a specific example where you ran into problems? Maybe there are other options I'm missing.

**Comment by niomaster** [comment]
specifically I need it in https://github.com/utwente-fmt/vercors/pull/519/commits/97ca8b9ac1539e0dc9f3db96897d78cec5f6b137, you can try that commit with this (C language):

```
#include <opencl.h>

/*@
    requires \pointer_index(a, get_global_id(0), write);
@*/
__kernel void example(int a[]) {
    int tid = get_global_id(0);
    a[tid] = tid;
}
```

**Comment by niomaster** [comment]
I think the best solution is to untangle the confusion between proof steps and ghost parameters in the COL AST, so we'd have a node for "ghost parameter mappings" and the regular with/then. I think for now I'm okay with (A), since many passes make incorrect assumptions on the format of with/then I think and we can deal with that once we untangle the nodes.

**Comment by bobismijnnaam** [comment]
Your problem seems unrelated to the with/then limitation I mentioned. It is due to the non-null type check on line 80 in NameScanner. I think this check is inconsistent with the rest of the code, so it should probably be removed. NameScanner will then still function correctly, but it won't compute the types of free variables given an untyped ast (which sounds appropriate). When applying the fix your example seems to get to viper without crashing (but it does not verify. I think that might be a different problem). I can open a PR for this change tomorrow or you can apply the fix in your branch if we choose this direction.

**Comment by niomaster** [comment]
If I understand you correctly the issue is resolved when the `requireNonNull` line is removed entirely, and it's okay that there's `Entry`'s with a `null` `typ`? If so, I'll just apply that in the branch I need it in and be done with it. Thanks :)

**Comment by bobismijnnaam** [comment]
Closing this because your use-case is resolved. Or, if you want to keep this issue to track the shortcoming of NameScanner, feel free to open it again.
