### ISSUE TITLE
Cannot use requires for parallel block iterator argument

### ISSUE THREAD

**Issue by bobismijnnaam** [utwente-fmt/vercors#521]
I expect the following program to verify:

```
class Foo {
  requires xs != null;
  void bar(int[] xs) {
      par (int tid = 0 .. xs.length)
      requires xs != null;
      {

      }
  }
}

```

Instead, it does not:

```
=== temp.pvl                       ===
   2   requires xs != null;
   3   void bar(int[] xs) {
                             [---------
   4       par (int tid = 0 .. xs.length)
                              ---------]
   5       requires xs != null;
   6       {
-----------------------------------------
  ApplicationPreCondition:AssertionFalse
=========================================
=========================================
auxiliary in Generated OptionGet code: Array access to value which may be null:
  caused by
=========================================
=== temp.pvl                       ===
   2   requires xs != null;
   3   void bar(int[] xs) {
                             [---------
   4       par (int tid = 0 .. xs.length)
                              ---------]
   5       requires xs != null;
   6       {
-----------------------------------------
  ApplicationPreCondition:AssertionFalse
=========================================
=========================================
auxiliary in Generated OptionGet code: Array access to value which may be null:
  caused by
=========================================

```

Using ```context_everywhere``` for the region contract allows it to verify, but I think this is not the intended use of `context_everywhere`.

```
class Foo {
  requires xs != null;
  void bar(int[] xs) {
      context_everywhere xs != null;
      par (int tid = 0 .. xs.length)
      {

      }
  }
}
```

I think this happens because the moment when `context_everywhere` is applied is not properly defined. This happens (probably among other places) in `do_block` in `ParallelBlockEncoder`. Not sure if this is a bug, but the `invariant` member of `Contract` gets appended to the `main_cb`, but not to the `body_cb`. I think this is part of the problem, but it needs more investigation.

I think the semantics that would be useful here is that the contract of the block also covers the evaluation of the parallel block selector (the `0 .. xs.length` part), while now the effective semantics is that you have to cover the conditions needed for the selector in the region contract, separate from the parallel block contract.

**Comment by niomaster** [comment]
The first one actually implies a pretty annoying problem, if you take:

```
par(i = 0..len(ar))
requires ar != null
requires Perm(ar[i], write)
{}
```

Is the thread contract now:

```
requires 0 <= i && i < len(ar) // not framed correctly
requires ar != null
requires Perm(ar[i], write)
```

or:

```
requires ar != null
requires Perm(ar[i], write) // not framed correctly
requires 0 <= i && i < len(ar)
```

**Comment by niomaster** [comment]
Maybe also related: https://github.com/utwente-fmt/vercors/issues/241 (we intend to copy boolean invariants to the thread contract)

**Comment by bobismijnnaam** [comment]
Hmm, so to solve this, when you use a dereferencing expression in the selector, you need to specify both the region contract and the block contract manually to circumvent this problem? This workaround currently doesn't work either, since I added two requires (one before `par` and one after) and that failed as well. I guess we've never run into this before as I haven't heard anyone complain about this (maybe @Safari1991?), but it feels very inelegant/syntactically heavy.

**Comment by niomaster** [comment]
I think a good condition for generating the region contract automatically is whether the supplied region contract is boolean, instead of being empty.
