### ISSUE TITLE
Remove distinction between java-check and check?

### ISSUE THREAD

**Issue by niomaster** [utwente-fmt/vercors#527]
I think we should drop the distinction between java-check and check. The one true type check should reflect what we consider a well-formed COL AST. It's fine if java-specific things are in there, but let's then model them as separate ASTNode's. Any opinions?

**Comment by bobismijnnaam** [comment]
I agree. I can't think if any reason not to go in this direction, only that it might be challenging.

**Comment by niomaster** [comment]
There is no longer such a distinction.
