### ISSUE TITLE
Star imports

### ISSUE THREAD

**Issue by niomaster** [utwente-fmt/vercors#548]
Sonar complains that `.*` imports are dangerous. IntelliJ auto-formats imports in such a way that highly-imported packages reduce to `*` automatically. Can we disable this in sonar, or if someone feels very strongly against this find the setting in intellij to disable it?

**Comment by Sophietje** [comment]
Haven't tested it yet, but I believe I have disabled the specific rule that
this is responsible for this check (called "Wildcard imports should not be
used").

**Comment by bobismijnnaam** [comment]
I turned it on to investigate if following the google style guide would be a problem. Indeed if we decide to follow this we should also investigate if we can configure intellij in a project-dependent manner, such that people working on vercors don't have to change their IDEs for style preferences like this. But for now turning it off is totally fine with me.
