### ISSUE TITLE
When lifting declarations, only argument are exhaled, not locals

### ISSUE THREAD

**Issue by pieter-bos** [utwente-fmt/vercors#549]

**Comment by bobismijnnaam** [comment]
Does this problem occur when verifying certain inputs or is it more of an architectural issue?

**Comment by niomaster** [comment]
It is an architectural problem. It also seems the pass is flawed in more ways (e.g. declarations from bindings are incorrectly lifted as well; abstract methods gain a body purely to exhale lifted arguments)

**Comment by pieter-bos** [comment]
Duplicate of #921
