### ISSUE TITLE
Scoping issue for generated triggers

### ISSUE THREAD

**Issue by OmerSakar** [utwente-fmt/vercors#551]
Han (the Master student) came across a problem where an existential quantifier in a universal quantifier caused scoping issues.

The issue is introduced after the pass gen-triggers. In the (minimized) example below the expression `eq(a,b)` is chosen as a trigger for the universal quantifier. However, `AbstractTypeCheck` then complains that `a` (in the trigger) is undefined (see the error message below). 

```
class GenTriggers {
    pure boolean myfunc() =
	    (\forall int b; 0 >= b;
	        (\exists int a; 0 <= a;
	            eq(a,b)
	        )
	    );

    pure boolean eq(int a, int b) = a == b;
}
```

```
=== scoping.pvl                 ===
   3 	    (\forall int b; 0 >= b;
   4 	        (\exists int a; 0 <= a;
                   [-
   5 	            eq(a,b)
                    -]
   6 	        )
   7 	    );
-----------------------------------------
  Local name a is undefined
=========================================
```

**Comment by niomaster** [comment]
So: a trigger may only contain names that are free in the whole body of the quantified expression. NameScanner would yield a list of allowed names if we scan the body, except we can redeclare names: `\forall int i; valid_trigger(i) && \exists int i; invalid_trigger(i)`, which in fact should allow `valid_trigger` but not `invalid_trigger`.

Maybe an approach is to check the `site` of names and collect all sites in the body of the quantifier?

**Comment by bobismijnnaam** [comment]
> except we can redeclare names

Is there a reason why we are so lenient on this? Both C and Java disallow reusing local variable names (though, C allows shadowing a global variable with a local variable, and Java has a rule for locals/instance variables). Maybe the situation is easier if we disallow your example? Being lenient is nice for prototyping specs, but in the end it also makes the specs (possibly) unclearer. (Unsure where my own preference is in this case)

**Comment by niomaster** [comment]
I still strongly prefer to focus on improving our reasoning about names, in particular we should just not care about the exact names of declarations.

**Comment by bobismijnnaam** [comment]
Would the `site` contain the AST node where the name was defined? That is, a concrete AST node, such as a `DeclarationStatement`, `BindingExpression`, or `Method`. How many sites would there be in your valid/invalid example (2: `\forall int i ...` and `\exists int i ...`? Or is it about the `DeclarationStatement`s _inside_ the `BindingExpression`s)

**Comment by bobismijnnaam** [comment]
> Maybe an approach is to check the site of names and collect all sites in the body of the quantifier?

So if I understand correctly, `NameScanner` would then aggregate all sites in the expression that are free (instead of just strings), and then gen-triggers would have more information about if a `NameExpression` is usable since it could check if the site is present in the list of free `DeclarationStatement`s.

To adjust this in NameScanner I think you only have to replace `String` everywhere with `DeclarationStatement`, and `getName` with `site`. So probably not too much work (haven't checked the code though). We could also add an interface that keeps the old `String` interface (as it can be easily derived if you have all the sites) intact for old clients of `NameScanner`.

**Comment by niomaster** [comment]
Isn't the defining property of a free name that it has no site in some expression? However, we can collect non-free names as declarationstatements :)

**Comment by bobismijnnaam** [comment]
I guess this depends on context. In the snippet `forall int i; f(i, j)` I'd say j is free and has no site. But if this snippet is part of the contract clause `ensures forall int i ...` I expect that j either refers to a field or an argument of the method, and hence it has a DeclarationStatement as site, right?

So I guess we should properly define what "having a site" means, for which I'd say it has a site if `site` is set...?

As NameScanner often operates on fragments of of the ASt this sounds useful.
