### ISSUE TITLE
Method calls in sequence update get dereferenced with -> operator

### ISSUE THREAD

**Issue by HanHollander** [utwente-fmt/vercors#554]
When updating a sequence with the S[i -> v] syntax but with methods like in the program below, it produces an error.

```
class MyClass {

    static pure int find();

    static pure seq<int> unite(seq<int> S) =
        S[find() -> find()];

}
```

Error:
```
[debug] At AbstractTypeCheck.java:1034:
At null: Types of left and right-hand side argument are uncomparable: Integer/<<null>>
```

This is caused by the -> operator being interpreted as a dereference instead of an update:
`static /*@pure@*/ seq<int> /*@ pure */ unite(seq<int> S)=S [ (find() != null ==> find().find()) ];`

**Comment by niomaster** [comment]
Thanks for reporting! This is (apparently) intended syntax in Java and PVL, which makes it a question of parsing ambiguity:

```
nonTarget
 : // (...)
 | nonTarget '[' expr '->' expr ']'
 | nonTarget '->' identifier tuple
```

To be clear: the intended meanings are:

* `xs[i -> x]`: replace the value at index `i` in sequence `xs` with the value `x`
* `x->f(args)`: `x != null ==> x.f(args)`, where `f` is usually a predicate

Of course `xs[i -> computedValue()]` should be completely legal, so we need to untangle the ambiguity. Any suggestions?

**Comment by bobismijnnaam** [comment]
> x->f(args): x != null ==> x.f(args), where f is usually a predicate

~Is this used in the test suite?~ It's actually used quite a bit...

We can either change the map syntax, or change the predicate syntax, or both.

For the map syntax, we could maybe move to `index: value` syntax, though not sure what `:`-related ambiguities might arise then. 

For the predicate, we could adopt an elvis operator/null-coalescing operator like syntax, i.e. `x?.f(args)`, though that might be a bit cryptic (_but_, in line with what recent programming languages are doing)... Maybe we add an extra `-` to the arrow? Oh wait, that conflicts with `--`... How about we add 2 dashes? `x--->f(args)` :-)

Maybe as a final thought, in c++ `->` means pointer+field dereference. So maybe we should think of an alternative for both, so problems for this can be prevented in the c++ frontend. (cc: @OmerSakar)

**Comment by niomaster** [comment]
* the sequence update syntax will change to something like `seq.update(idx, val)`
* the predicate operator will become some form of the elvis operator, `?.` or `.?`
* @OmerSakar will look into a solution for the explicit map syntax (but in the meantime it's easy to disambiguate with parentheses)
