### ISSUE TITLE
Using function arguments in set comprehension is not possible

### ISSUE THREAD

**Issue by HanHollander** [utwente-fmt/vercors#557]
When using set comprehension in a function body, it is currently not possible to use any arguments of that function in the condition of the set comprehension.

The following example produces an error:

```
class Test {

    set<int> func(int N) {
        return set<int> {i | int i; 0 <= i && i < N};
    }

}
```

```
=== examples/scc/setcomp.pvl       ===
   3 
   4     set<int> func(int N) {
                                                     [-
   5         return set<int> {i | int i; 0 <= i && i < N};
                                                      -]
   6     }
   7 
-----------------------------------------
  Argument name N is undefined
=========================================
```

**Comment by niomaster** [comment]
I'm assuming the root cause of this has something to do with a problem in extracting the comprehension to a new method/function. That happens in multiple places in VerCors, so we should consider making a generic way to extract a snippet of code from the AST.

**Comment by OmerSakar** [comment]
Yes, that is exactly the issue (moving the comprehension to a new function). And yes, a generic way to extract a snipper to a function would be great. As far as I know, the only place this is currently done is the parallel blocks, right?

**Comment by niomaster** [comment]
Insofar I can think of right now, yes. You might also count the passes that generate a duplicate method in some form, but those are easy cases probably (`sat_check` and I think `java_encode`)

**Comment by pieter-bos** [comment]
See here for discussion: <https://github.com/utwente-fmt/vercors/discussions/1068>
