### ISSUE TITLE
OpenCL: Expecting fail when ensuring things about array out of bounds

### ISSUE THREAD

**Issue by sakehl** [utwente-fmt/vercors#562]
## Expected Behavior
When running the following program:
```opencl
#include <opencl.h>
/*@
  context_everywhere opencl_gcount == 1;
  context_everywhere opencl_gsize >= 100;
  
  context_everywhere \array(u_new,100);
  context_everywhere \array(u, 100);
  context_everywhere nx == 200;

  context \pointer_index(u, \ltid , read);
  context \pointer_index(u_new, \ltid , write);

  ensures \ltid < nx - 1 ==>
   u_new[\ltid] == \old(u[\ltid]) + 1;
  ensures !(\ltid < nx - 1) ==>
   u_new[\ltid] == \old(u[\ltid]);
@*/
__kernel void diffuse_kernel(int u_new[], int u[], int nx) {
  int tid = get_local_id(0);
  int i = tid;
  if(i < nx - 1)
    u_new[i] = u[i] + 1;
  else if (i == nx - 1)
    u_new[i] = u[i];
}
```
I would expect a fail, I wrote this program incorrectly. Since we require this program to work for any group size that is bigger than 100. And we ensure that for local thread ids that are **not** smaller than (nx-1), this to hold: `u_new[\ltid] == \old(u[\ltid])`. We also require read and write access for those thread ids. 

But let's take as `opencl_gsize == 300` (which is possible, since `opencl_gsize >= 100`). Now apparently it is ok to get read and write permission for `u` and `u_new`, also for threads with id >= 100, even though the arrays have size 100.

And we require for instance that `u_new[150] == \old(u[150])` should hold, which the kernel is out of array bounds. Furthermore, we require `u_new[250] == \old(u[250])` to hold, which the kernel doesn't even set (and is out of bounds).

Unless I'm completely missing the point somewhere, this seems incorrect.

## Current Behavior
Get a pass.

## Possible Solution
It seems that it is related to `context_everywhere opencl_gsize >= 100`. When changing that to for instance
`context_everywhere opencl_gsize == 101` we do get a fail.

## Steps to Reproduce
1. Installed development version of vercors. This is the version
```
$ vct --version
Vercors 1.3.0-SNAPSHOT
Built by sbt 1.3.8, scala 2.12.10 at 2020-09-15T10:31:07.121Z
On branch dev, commit 526841e8e,
```
2. Run vercors like: $ vct --silicon --lang=opencl ensure_bug.c
3. This is the output:
```
$ vct --silicon --lang=opencl ensure_bug.c 
clang: warning: argument unused during compilation: '-nocudainc' [-Wunused-command-line-argument]
Success!
The final verdict is Pass
```

**Comment by niomaster** [comment]
The problem here is that VerCors allows you to specify `\array` over a pointer. The `true' length of a pointer should be inaccessible from the frontend, but you can in effect specify it via `\array`.

`\array(u, 100)` implies that `\length(u) == 100`. In the kernel proof we have due to `\pointer_index` again `\forall 0 <= \ltid < opencl_gsize . \ltid < \length(u)`, which is reduced to just `opencl_gsize <= \length(u)`. Since `\length(u) == 100` we have both `opencl_gsize >= 100` and `opencl_gsize <= 100`, i.e. `opencl_gsize == 100`. Requiring anything that contradicts this makes the kernel precondition unsatisfiable, allowing you to prove anything in the body and postcondition. If you add for example `opencl_gsize == 101`, VerCors warns you of this fact:

```c
#include <opencl.h>
/*@
  context_everywhere opencl_gcount == 1;
  context_everywhere opencl_gsize == 101;

  context_everywhere \array(u_new,100);
  context_everywhere \array(u, 100);
  context_everywhere nx == 200;

  context \pointer_index(u, \ltid , read);
  context \pointer_index(u_new, \ltid , write);

  ensures \ltid < nx - 1 ==>
   u_new[\ltid] == \old(u[\ltid]) + 1;
  ensures !(\ltid < nx - 1) ==>
   u_new[\ltid] == \old(u[\ltid]);
@*/
__kernel void diffuse_kernel(int u_new[], int u[], int nx) {
  int tid = get_local_id(0);
  int i = tid;
  if(i < nx - 1)
    u_new[i] = u[i] + 1;
  else if (i == nx - 1)
    u_new[i] = u[i];
}
```

outputs:

```
$ vercors --silicon vercors/examples/private/562.cl 
clang: warning: argument unused during compilation: '-nocudainc' [-Wunused-command-line-argument]
Errors! (1)
=== vercors/examples/private/562.cl ===
-----------------------------------------
  in branch contract satisfiability check:
  MethodPreConditionUnsound:MethodPreConditionFalse
=========================================
The final verdict is Fail
```

I think the immediate solution here is to just remove the two `\array` lines, the `\pointer_index` specification should be sufficient.

**Comment by sakehl** [comment]
Hmm ok thanks for the clarification.

Maybe it's just a misinterpretation than from my side. Since I was expecting:
* For any chosen `opencl_gsize` >= 100, the given kernel is correct.
But it behaves like:
* There exists an `opencl_gsize` >= 100, for which the kernel is correct.

Although you are correct, when removing the two `\array` lines, I do get a satisfying result. Is there any other way to indicate the lengths of the arrays? Normally, you'd have to sent the data to the OpenCL kernel first by making buffers and sending them, but I expect this is not possible in Vercors, right?
