### ISSUE TITLE
Abstract Inline function with a postcondition using \result results in an NPE 

### ISSUE THREAD

**Issue by OmerSakar** [utwente-fmt/vercors#569]
The following piece of PVL code (without the class definition) results in an NullPointerException as found by Han Hollander):

```
requires |Q| <= |P|;
ensures \result == (\forall int i; 0 <= i && i < |Q|; Q[i] == P[i]);
static inline pure boolean subSeq123(seq<int> Q, seq<int> P);

void main(seq<int> P1, seq<int> Q1) {   
  assert subSeq123(Q1, P1);
}
```

The problem lies in the combination of an inline function that is abstract and has a postcondition that uses `\result`.

Besides the NPE, I think there are several things we have to consider (which will solve the NPE as well):

- What does the contract of the inline function actually do? It is currently allowed syntactically (as it should), however, there is no check to disallow it. In the Silver output, the contract is just thrown away. We should either disallow it or have them as proof hints (as @niomaster suggested).
- Should a function be allowed to be inline AND abstract? It does not make sense to inline a function without a body, so we could just disallow it. However, we could also consider not inlining it if it is abstract. This should be okay if, in case of a concrete function (with a body), we use the contract as proof hints.

**Comment by niomaster** [comment]
re: inline and abstract, we should also consider inheritance constraints there
