### ISSUE TITLE
Rewrite rules only work on int arrays, not other arrays

### ISSUE THREAD

**Issue by ArmborstL** [utwente-fmt/vercors#576]
The rewrite rules, e.g. for `Perm(arr[*], p)`, only work if `arr` is an integer array, not e.g. for a boolean array.

As a solution, the definition of `int[] ar` should be replaced with `_AnyTypeForSimplificationRules[] ar` at least in 
* `src/main/universal/res/config/simplify_quant_pass1.jspec` Line 152 
* `src/main/universal/res/config/simplify_quant_pass2.jspec` Line 11

(potentially other places, too?)

**Comment by bobismijnnaam** [comment]
If you happen to have an example laying around, could you include it? I expect the case is almost trivial, with just "Perm" in the requires, right?

**Comment by ArmborstL** [comment]
I didn't have a simple example, but it was indeed trivial to create one:
```pvl
class T{
    boolean[] arr;
    
    resource r() = Perm(arr, read) ** arr!=null ** Perm(arr[*], 1\2);
}
```
This crashes the silver transformation, but verifies if you use `int[]` instead of `boolean[]`.

**Comment by niomaster** [comment]
they work on other arrays now.
