### ISSUE TITLE
omitted accessible/modifies keyword creates unclear error.

### ISSUE THREAD

**Issue by Jankoekenpan** [utwente-fmt/vercors#600]
Using --check-history on the Future

```
class `Future` {

    int myVar;

    //accessible myVar;
    requires myVar == 0;
    process p();

}

```

VerCors complains that `Local name myVar is undefined` because it not a parameter of the process p. It is however a field. A workaround for the issue is to uncomment the line with `accessible` or `modifies` so that VerCors properly understand that the field should be used.

It would be nice if

- the error message could be improved (e.g. suggest possible fixes for the issue)
or
- it is automatically detected that the field should be used.

As a second issue: running with `--show-after checkHistory` did not print the AST either.

**Comment by niomaster** [comment]
The error message is clearer, we'll see about auto-detection when we reconsider the process model implementation.
