### ISSUE TITLE
AbstractPrinter doesn't preserve order of contract pre- and postcondition

### ISSUE THREAD

**Issue by petravandenbos-utwente** [utwente-fmt/vercors#619]
```requires a; requires b; ensures b; ensures a;```
is transformed as 
```context a; context b;```
is parsed as
```requires a; requires b; ensures a; ensures b;```

**Comment by pieter-bos** [comment]
We currently just always print `requires`/`ensures` separately, even with `context` in the input. Given that we have no concept in the AST to encode `context` (other than just duplicating them into `requires`/`ensures`) I think this is the best we can do for now.
