### ISSUE TITLE
Improve support for set comprehension

### ISSUE THREAD

**Issue by ArmborstL** [utwente-fmt/vercors#621]
Right now, the support for set comprehension is limited. For instance #557 highlights that local variables (like function arguments) cannot be used in the comprehension.
Another shortcoming is that the source expression for the variable is limited, e.g. `int x <- { 0 .. maxVal }` is not supported right now. It would be nice to support not just a small set of collectionConstructor expressions there, but more generic expressions (e.g. also `int x <- xs + ys`).

**Comment by bobismijnnaam** [comment]
Small remark: `\forall` also has a range syntax (I think it is: `(\forall int i = 0 .. 10; p(i))`). If this issue improves/changes the notation for set comprehension, we should also change the syntax for quantifiers for consistency.

**Comment by pieter-bos** [comment]
See here for discussion: <https://github.com/utwente-fmt/vercors/discussions/1068>
