### ISSUE TITLE
Better management of the .classpath file

### ISSUE THREAD

**Issue by bobismijnnaam** [utwente-fmt/vercors#631]
The `bin/.classpath` file can currently get out of sync with the project.

To make the interface more intuitive, `bin/.classpath` should be deleted when the sbt `clean` task is executed. This is already in `build.sbt`, but because of a bug sbt doesn't actually delete the file on clean. This should be fixed in sbt 1.5, so upgrading sbt will improve the situation already.

To completely fix it, I propose that the `compile` action of sbt also writes to `bin/.classpath`. I think this can be achieved by overriding the `compile` action in `build.sbt` to also write to the `bin/.classpath` file.

**Comment by niomaster** [comment]
The classpath is computed from the build files, and sbt only updates the build files on reload. It would make more sense to hook the .classpath update to reload and/or startup then.

**Comment by bobismijnnaam** [comment]
Yes, that's also okay, as long as compilation also updates it (e.g. when adding classes or subprojects the .classpath might need to be updated?). Specifically, the ideal behaviour I would like is: if you've compiled vercors since you've made changes or added any of the source files, the `bin/.classpath` file is up to date.

**Comment by niomaster** [comment]
The types of changes you list sketch exactly the distinction between compilation an reloading:

- "adding classes ~or subprojects~": if sbt compiles them, they are guaranteed to be under a classpath that sbt already knows about, and hence `.classath` already knows about. Compilation is guaranteed not to change the classpath.
- "~adding classes~ or subprojects": sbt cannot load or change out new (sub)projects while running, and will not compile any new code in a new project, or drop projects that are moved/deleted. Only when you reload the project, or restart sbt entirely, sbt knows about the new project. Correspondingly, the class path is not updated if you change the project structure while sbt is running, so it will not help to update `.classpath` after a compile in that case.

**Comment by bobismijnnaam** [comment]
Interesting, then start/reload indeed seems to be all we need.
