### ISSUE TITLE
merge dev to ast

### ISSUE THREAD

**Issue by Vescatur** [utwente-fmt/vercors#643]

**Comment by bobismijnnaam** [comment]
What was the issue here, and can it be closed after merging #644?

**Comment by bobismijnnaam** [comment]
@Vescatur Was the goal of this issue to track updating the ast branch with code from dev?

**Comment by Vescatur** [comment]
What exactly do you mean by tracking the updating of the ast branch? I suppose the goal of the issue was to update ast from the code of dev.
