### ISSUE TITLE
Processes with modifies clauses

### ISSUE THREAD

**Issue by wytseoortwijn** [utwente-fmt/vercors#65]
Processes may be associated with `modifies` clauses. However, at the moment modifies clauses only accept one entry. To illustrate, VerCors gives an exception with the following code sample:
```java
class Future {
  int a;
  int b;

  modifies a,b;
  process test();
}
```

If we change the program to `modifies a`  or `modifies b` (or both, combined, by having two `modifies` clauses) the program is accepted.

**Comment by niomaster** [comment]
Although process models are not yet done, the parsing+resolving part of this is done as of 785df4dee2b6c9f9bb85771e3e82a4ac63e3ae96
