### ISSUE TITLE
Wiki link does not work

### ISSUE THREAD

**Issue by Vescatur** [utwente-fmt/vercors#653]
The link "website" in https://github.com/utwente-fmt/vercors/wiki/Specification-Syntax goes to a "no result" page.

https://vercors.ewi.utwente.nl/try_online/examples?ExampleSearch%5Bid%5D=&ExampleSearch%5Btitle%5D=&ExampleSearch%5Bfeature%5D=&ExampleSearch%5Bsource%5D=1&ExampleSearch%5Blanguagename%5D=

**Comment by raulmonti** [comment]
Works for me o.O
Did you already fix it? or is it randomly not working?
