### ISSUE TITLE
Check for unsupported use of wildcard

### ISSUE THREAD

**Issue by bobismijnnaam** [utwente-fmt/vercors#668]
According to https://github.com/viperproject/silver/issues/534, `read` permissions are currently not allowed in complex expressions (e.g. `Perm(x.f,  i == 0 ? read : 1 \ 2)` is not allowed), as the desired semantics is not yet clear. Instead, `read` should only appear as a literal argument to `Perm`. Therefore, we should check the AST and disallow this usage in the viper phase of vercors.

On an additional note, if there are any specific forms we would like to have support for, an issue can be filed with viper/silicon/carbon.

**Comment by bobismijnnaam** [comment]
In the new AST we can maybe make a distinction between `acc` and `Perm`, and have differen't typechecking rules for them (@niomaster). But in the old AST we should probably just fudge it in the viper passes.

**Comment by niomaster** [comment]
Yeah sure, there already is a `SilverPerm` and `SilverPredPerm` as opposed to `Perm`.
