### ISSUE TITLE
Proving termination

### ISSUE THREAD

**Issue by wytseoortwijn** [utwente-fmt/vercors#67]
We could implement support for simple termination proving by translating:
```java
decreases expr;
while (C) {
  S;
}
```
into:
```java
invariant expr >= 0;
while (C) {
   int old_expr = expr;
   S;
   assert old_expr > expr;
}
```

On the way back, "_invariant errors_" can be translated to "_decreases clause not well founded_" and "_assertion failures_" mean that "_the decreases clause is not decreasing_".

**Comment by sjcjoosten** [comment]
There's a nicer way to do it, which uses tokens, as detailed in this TACAS paper: https://link.springer.com/chapter/10.1007/978-3-319-89960-2_9

**Comment by Sophietje** [comment]
It seems like Viper nowadays supports a [decreases clause](http://viper.ethz.ch/tutorial/?page=1&section=#termination) to prove termination of a recursive function. Termination checks for methods and loops are still experimental.
