### ISSUE TITLE
The timing is behaving weird.

### ISSUE THREAD

**Issue by Vescatur** [utwente-fmt/vercors#690]
There are two things regarding the timing which should be investigated. I added the following line to the output. "[progress] [03%] resolveTypeExpressions completely took 46 ms" This shows the total time the task takes. I think the line "[progress] [03%] resolveTypeExpressions took 15 ms" is pretty misleading because it actually took a lot longer then that. By also showing the complete time it would inform the user of the overhead required.
The second thing I find odd is the time between the line "[progress] [96%] collectDeclarations completely took 250 ms" and "[progress] [100%] applySilicon completely took 828 ms" is 828ms however this line "[progress] task Viper verification took 3299 ms" says a task took 3299ms. I am not sure which one but one of them would need to be incorrect. 

[progress] parsing inputs...
[progress] Parsing c file examples\clang\c-example-use.c
[progress] pre-processing command line: clang -C -E -nostdinc -nocudainc -nocudalib --cuda-host-only -isystem C:\Users\Ivan\Documents\Develop\vercors4\vercors\src\main\universal\res\include -IC:\Users\Ivan\Documents\Develop\vercors4\vercors\examples\clang -
clang: warning: argument unused during compilation: '-nocudainc' [-Wunused-command-line-argument]
[progress] first parsing pass took 343ms
[progress] AST conversion took 93ms
[progress] Read examples\clang\c-example-use.c successfully
[progress] Parsed 1 file(s) in: 484ms
[progress] [03%] resolveTypeExpressions took 15 ms
[progress] [03%] resolveTypeExpressions completely took 46 ms
[progress] [07%] loadExternalClasses took 15 ms
[progress] [07%] loadExternalClasses completely took 62 ms
[progress] [10%] wrapTopLevelDeclarations took 15 ms
[progress] [10%] wrapTopLevelDeclarations completely took 46 ms
[progress] [14%] removeUnusedExternMethods took 15 ms
[progress] [14%] removeUnusedExternMethods completely took 62 ms
[progress] [17%] specifyImplicitLoopLabels took 15 ms
[progress] [17%] specifyImplicitLoopLabels completely took 46 ms
[progress] [21%] propagateAbstractMethodContracts took 15 ms
[progress] [21%] propagateAbstractMethodContracts completely took 62 ms
[progress] [25%] arrayNullValuesToNone took 15 ms
[progress] [25%] arrayNullValuesToNone completely took 62 ms
[progress] [28%] addRequirementSatCheck took 15 ms
[progress] [28%] addRequirementSatCheck completely took 78 ms
[progress] [32%] checkAssignInPar took 15 ms
[progress] [32%] checkAssignInPar completely took 78 ms
[progress] [35%] dummy-InvariantsPropagatedHere took 0 ms
[progress] [35%] dummy-InvariantsPropagatedHere completely took 78 ms
[progress] [39%] liftGhostCode took 15 ms
[progress] [39%] liftGhostCode completely took 78 ms
[progress] [42%] inlineWithThenHints took 15 ms
[progress] [42%] inlineWithThenHints completely took 78 ms
[progress] [46%] encodeParallelBlocks took 0 ms
[progress] [46%] encodeParallelBlocks completely took 62 ms
[progress] first parsing pass took 1078ms
[progress] AST conversion took 78ms
Could not find file: C:\Users\Ivan\Documents\Develop\vercors4\vercors\src\main\universal\res\config\java\lang\Object.java
[progress] first parsing pass took 218ms
[progress] AST conversion took 15ms
[progress] [50%] simplify took 2500 ms
[progress] [50%] simplify completely took 2562 ms
[progress] first parsing pass took 31ms
[progress] AST conversion took 15ms
[progress] [53%] simplifySums took 109 ms
[progress] [53%] simplifySums completely took 156 ms
[progress] first parsing pass took 15ms
[progress] AST conversion took 0ms
[progress] [57%] optimizeForSilver took 46 ms
[progress] [57%] optimizeForSilver completely took 78 ms
[progress] [60%] desugarArrayOps took 15 ms
[progress] [60%] desugarArrayOps completely took 62 ms
[progress] [64%] flattenNestedExpressions took 15 ms
[progress] [64%] flattenNestedExpressions completely took 62 ms
[progress] [67%] encodeInheritanceToDomain took 15 ms
[progress] [67%] encodeInheritanceToDomain completely took 62 ms
[progress] [71%] importADTsAndRefEncode took 1953 ms
[progress] [71%] importADTsAndRefEncode completely took 2031 ms
[progress] [75%] returnTypeToOutParameter took 46 ms
[progress] [75%] returnTypeToOutParameter completely took 234 ms
[progress] [78%] reduceQuantifierNesting took 46 ms
[progress] [78%] reduceQuantifierNesting completely took 218 ms
[progress] [82%] inlinePatternsToTriggers took 46 ms
[progress] [82%] inlinePatternsToTriggers completely took 218 ms
[progress] [85%] generateQuantifierTriggers took 31 ms
[progress] [85%] generateQuantifierTriggers completely took 203 ms
[progress] [89%] scaleAllPredicateApplications took 62 ms
[progress] [89%] scaleAllPredicateApplications completely took 250 ms
[progress] [92%] collectInnerDeclarations took 46 ms
[progress] [92%] collectInnerDeclarations completely took 234 ms
[progress] [96%] collectDeclarations took 46 ms
[progress] [96%] collectDeclarations completely took 250 ms
[progress] verifying with builtin silicon backend
[progress] conversion took 62ms
Success!
[progress] task Viper verification took 3299 ms
[progress] [100%] applySilicon took 656 ms
[progress] [100%] applySilicon completely took 828 ms
The final verdict is Pass
[progress] entire run took 15270 ms

Process finished with exit code 0

**Comment by niomaster** [comment]
Yes, we should make sure to look at "lost" time. There is exactly one valid reason why "time travel" can occur: most vercors tasks are measured in user-cpu-time (i.e. the amount of cycles we occupied on the processor divided by its frequency), which is more stable for measurements than wall time (i.e. the amount of time elapsed in the real world). 828ms : 3299ms is suspect though.

**Comment by niomaster** [comment]
Will be investigated as part of #747
