### ISSUE TITLE
Create long term architect regarding static variables

### ISSUE THREAD

**Issue by Vescatur** [utwente-fmt/vercors#691]
Before ScalaTest a process is used only once for verifying code. Now it is used multiple time which causes issue with the static code. I tried to make the least amount of changes to make it work however it might be nice to think about this long term. Specifically the classes System, Configuration, rewriteArrayRef and Flatten.

**Comment by niomaster** [comment]
There is now virtually no global state, and vercors can be invoked in a functional way (i.e. no options)
