### ISSUE TITLE
NullPointerExceptions

### ISSUE THREAD

**Issue by AVeenstra** [utwente-fmt/vercors#70]
- `./unix/bin/vct --silver` results in: `java.lang.NullPointerException
        at vct.main.Main.main(Main.java:242)`
- `./unix/bin/vct --silver=silicon test.cl` with test.cl as `__kernel  void main() {}` results in:
  > remaining type of  is Void
  > Triggered by file test2.cl from line 1 column 1 until line 1 column 23:
  > java.lang.NullPointerException
  >         at vct.col.rewrite.KernelBodyRewriter.visit(KernelBodyRewriter.java:66)
  >         at vct.col.ast.Method.accept_simple(Method.java:204)
  >         at vct.col.ast.ASTNode.accept(ASTNode.java:166)
  >         at vct.col.ast.ASTNode.apply(ASTNode.java:221)
  >         at vct.col.rewrite.AbstractRewriter.rewrite(AbstractRewriter.java:227)
  >         at vct.col.rewrite.ConvertTypeExpressions.visit(ConvertTypeExpressions.java:80)
  >         at vct.col.ast.Method.accept_simple(Method.java:204)
  >         at vct.col.ast.ASTNode.accept(ASTNode.java:166)
  >         at vct.col.ast.ASTNode.apply(ASTNode.java:221)
  >         at vct.col.rewrite.AbstractRewriter.rewrite(AbstractRewriter.java:227)
  >         at vct.col.rewrite.AbstractRewriter.rewriteAll(AbstractRewriter.java:543)
  >         at vct.col.rewrite.ConvertTypeExpressions.rewriteAll(ConvertTypeExpressions.java:89)
  >         at vct.antlr4.parser.ColIParser.parse(ColIParser.java:62)
  >         at vct.antlr4.parser.ColCParser.parse(ColCParser.java:60)
  >         at vct.antlr4.parser.Parsers.parseFile(Parsers.java:42)
  >         at vct.main.Main.main(Main.java:265)
  > Exception class java.lang.NullPointerException while parsing test2.cl
  > java.lang.Exception: Stack trace
  >         at java.lang.Thread.dumpStack(Thread.java:1336)
  >         at hre.lang.System.Abort(System.java:29)
  >         at vct.antlr4.parser.ColCParser.parse(ColCParser.java:65)
  >         at vct.antlr4.parser.Parsers.parseFile(Parsers.java:42)
  >         at vct.main.Main.main(Main.java:265)
  > The final verdict is Error

    seems as if the nullpointer is thrown at every kernel without verification

**Comment by sjcjoosten** [comment]
Could you attach test.cl?

**Comment by AVeenstra** [comment]
`test.cl` is litarally just:

```
__kernel void main() {}
```

If I remember correctly I tried other kernels without any verification just to see if it would parse.

If you want more examples my comment on issue #71 should provide some.

**Comment by niomaster** [comment]
Some basic support for OpenCL and cuda kernels should be added via #361 soonish. `--silver` crashing vercors is a problem in the flags system, so moving this issue there.

**Comment by niomaster** [comment]
Everything relating to options and/or OpenCL has been refactored since this issue, so a mostly empty file will certainly work.
