### ISSUE TITLE
Local variables can have races in parallel blocks

### ISSUE THREAD

**Issue by sjcjoosten** [utwente-fmt/vercors#73]
I argue we should treat local variables as heap locations in parallel blocks. Consequently, permissions to local variables must be given in parallel blocks. Attached is a program that illustrates the issue.

Please comment if you fear the fix might cause any correct programs to no longer verify.
[non_heap_race.pvl.zip](https://github.com/utwente-fmt/vercors/files/1733942/non_heap_race.pvl.zip)

**Comment by wytseoortwijn** [comment]
Theoretically, in CSL, the proof rule for parallel blocks has a premise to deal with races on the stack.

Practically, this might be a solution, but I don't think Viper directly accepts it, since 'x' is not shared memory; one probably cannot encode this as 'acc(x)' into Silver.

**Comment by wytseoortwijn** [comment]
Does VerCors actually take this program as input? I'm getting an exception saying that the `type of j is null` when running `vct --silver=silicon non_heap_race.pvl`.

**Comment by sjcjoosten** [comment]
Sorry for initially attaching the wrong file, should be fixed now!

**Comment by wytseoortwijn** [comment]
The listing below shows the Silver code that VerCors generates for this example. Notice that `x` is of type `Int`. In order to assign permissions to `x` we would need to have `x` be of type `Ref`. We could just build a wrapper for this.

```
method Main__loop_body_7(diz: Ref, global: Ref, current_thread_id: Int, x: Int, j: Int)
  requires diz != null
  requires global != null
  requires current_thread_id >= 0
  requires (0 <= j) && (j < 2)
  requires j < 2
  ensures (0 <= j) && (j < 2)
  ensures j < 2
{
  x := x + 1
}

method Main__parrallel_region_main_1(diz: Ref, global: Ref, current_thread_id: Int, x: Int)
  requires diz != null
  requires global != null
  requires current_thread_id >= 0
  requires (forall j: Int :: (0 <= j) && (j < 2) ==> (j < 2))
  ensures (forall j: Int :: (0 <= j) && (j < 2) ==> (j < 2))
{
  inhale false
}

method Main__main(diz: Ref, global: Ref, current_thread_id: Int) returns (sys__result: Int)
  requires diz != null
  requires global != null
  requires current_thread_id >= 0
{
  var x__1: Int
  var __flatten_2__2: Int
  // refute
  assert !false
  x__1 := 0
  Main__parrallel_region_main_1(diz, global, current_thread_id, x__1)
  __flatten_2__2 := x__1
  sys__result := __flatten_2__2
  // assert
  assert true
  inhale false
}

method Main__Main(global: Ref, current_thread_id: Int) returns (sys__result: Ref)
  requires global != null
  requires current_thread_id >= 0
  ensures sys__result != null
{
  var diz__3: Ref
  diz__3 := new()
  // refute
  assert !false
  sys__result := diz__3
  // assert
  assert sys__result != null
  inhale false
}
```

**Comment by bobismijnnaam** [comment]
Not sure if this is relevant, but at the moment I can't read local variables in parallel blocks:

```
class MyClass {
  void foo() {
    int x = 3;
    assert x > 0;
    par {
      assert x > 0;
    }
  }
}
```

Output:
```
running verify
finished verify
Errors! (1)
reporting AssertFailed error
=== par-read.pvl                   ===
   4     assert x > 0;
   5     par {
          [-------------
   6       assert x > 0;
           -------------]
   7     }
   8   }
-----------------------------------------
  AssertFailed:AssertionFalse
=========================================
=== par-read.pvl                   ===
   4     assert x > 0;
   5     par {
                 [-----
   6       assert x > 0;
                  -----]
   7     }
   8   }
-----------------------------------------
  caused by
=========================================
The final verdict is Fail
entire run took 4366 ms
```

Seems in the silver encoding that any constraints gathered before the parallel block are not passed on to the parallel block...?

**Comment by niomaster** [comment]
We now verify parallel blocks not by extracting a method, but locally via non-deterministic branching + constraining the heap with a `while`. Previously this was already resolved by banning writing to locals outside the scope of the parallel block, I think this functionality should be restored, although the current semantics (each `par` gets a copy of the local; the resulting local is some indeterminate final state of a par thread) is also explainable.
