### ISSUE TITLE
`given` clause not parsed at call site

### ISSUE THREAD

**Issue by Jankoekenpan** [utwente-fmt/vercors#743]
Using VerCors-2.0.0-Alpha-7 (https://github.com/Jankoekenpan/vercors/commit/6bdf1742af68e10fb1b0c9b4beeeb6d0a603deac#diff-c43195f6bd1133887be27f5d1aecb2af1140561041bcd9c710a3b5dedd262e07R797) (forked from https://github.com/utwente-fmt/vercors/commit/03895ae02121c9c46cf9eacfd0e9f84674459277)

```
[INFO] Starting verification
======================================
At examples\scc\SetBasedSCC_FSCC.pvl:797:21:
--------------------------------------
  795          R = seq<int> {};
  796          O = map<int, int> {};
                          [-----
  797          SetBased(v) given { predecessor = None };
                           -----]
  798      }
  799
--------------------------------------
Parsing failed: mismatched input 'given' expecting {'(', ')', '<', '>', '[', '.', '&&', '||', '^^', '>=', '<=', '==', '!=', '+', '-', '*', '/', '%', '++', '\in', 'in', 'then', 'given', '\', '**'}
======================================
```
Calling a method with a given clause in its contract does not work. According to the [transition guide](https://github.com/utwente-fmt/vercors/wiki/Transition-Guide#breaking-syntactical-changes) the keyword `given` should now be used instead of `with`. However, when doing so, VerCors does not recognise this clause (even though 'given' is in the set of expected tokens).

**Comment by niomaster** [comment]
`given`/`yields` is now syntactically restricted so that `given` has to appear after the name, but before the parentheses, and `yields` has to occur after the parentheses, like so:

```
callee given { x = 0 } () yields { recv = y };
```

I think this is rather ugly and has already caused a lot of confusion, so I suggest we back out this change, and/or allow given/yields in both positions.
