### ISSUE TITLE
Unicode forall in simplification rules does not parse on windows

### ISSUE THREAD

**Issue by bobismijnnaam** [utwente-fmt/vercors#751]
With vercors 2 alpha 8, on some recent version of windows, in the command prompt, when verifying a regular file, the following error occurs:

![Joel forall](https://user-images.githubusercontent.com/3082344/175031985-c195faa8-9195-4d58-a17a-e59a82d80688.png)

**Comment by niomaster** [comment]
Hmm, this is a strange one...

* All the binaries for this release were built on linux, where UTF-8 is the native encoding, so ANTLR should make the parsers/lexers for UTF-8 encoding.
* Regardless, we pass `"-encoding", "utf-8",` to ANTLR, so it should not matter
* `PathOrStd.getReader` forces UTF-8 as well:
```scala
  override protected def getReader: Reader = this match {
    case PathOrStd.Path(path) => new FileReader(path.toFile, StandardCharsets.UTF_8)
    case PathOrStd.StdInOrOut => new InputStreamReader(System.in, StandardCharsets.UTF_8)
  }
```

Open to any creative suggestions...

**Comment by niomaster** [comment]
Ah, `RWFile` is used specifically for library files, which was missing the forced charset.
