### ISSUE TITLE
Postcondition failure incorrectly reported + java.lang.Object constructor failing?

### ISSUE THREAD

**Issue by bobismijnnaam** [utwente-fmt/vercors#754]
I would expect a "postcondition failed" error in this case, but instead vercors tells me something about java.lang.Object:

```
$ cat p.pvl
ensures false;
pure int unknown0() =
    0;
$ ./bin/vct p.pvl
[INFO] Starting verification
An error condition was reached, which should be statically unreachable. `requires true` is always satisfiable.. Inner failure:
 > ======================================
 > At /home/bobe/Workbench/Tools/vercors_ast/src/main/universal/res/jdk/java/lang/Object.java:3:1:
 > --------------------------------------
 >     1  package java.lang;
 >     2
 >       [----------------
 >     3  class Object {
 >     4
 >     5  }
 >        -]
 >     6
 > --------------------------------------
 > The precondition of this contract may be unsatisfiable. If this is intentional, replace it with `requires false`. (https://utwente.nl/vercors#unsatisfiable)
 > ======================================
```

So the error report is two-fold:

1. VerCors should report the simpler contract-related error
2. In the grander scheme of things, java-concerns should be invisible to the user when verifying PVL.

**Comment by bobismijnnaam** [comment]
The problem here is that the following function is generated for silver:

```
function unknown0(): Int
ensures false
{
 0
}
```

Because it ensures `false`, this gives viper false as a global axiom somehow. This causes everything to pass, including all `assert false`'s, which in turn triggers the unsatisfiability check error.

The fix here is to not ensure `false`, but something like `\result == 1`. Somehow this is not a global alias for false.

Not sure if there is a fix for this as it depends on an implementation detail of one specific backend. If not this issue can be closed.

**Comment by niomaster** [comment]
> VerCors should report the simpler contract-related error

Although I agree with you in principle, I think it is good that VerCors prioritizes reporting internal inconsistencies above all other errors, so I think the error-reporting behaviour is correct with regards to the errors we get from viper.

> In the grander scheme of things, java-concerns should be invisible to the user when verifying PVL.

Yes, but I think this is clearly labeled as an internal consistency (but I'm happy to adopt a clearer wording)

> The fix here is to not ensure false, but something like \result == 1. Somehow this is not a global alias for false.

I believe the encoding is something like:

```
(forall h: Heap :: false)
```
vs
```
(forall h: Heap :: f(h) == 1)
```

In particular z3 in the first case uses the fact that the body is independent of `h`.

---

I think a good solution depends on two things: we should (1) recognize that we should not trust the result of verifying methods if the verification of the functions is incorrect, and (2) learn why the postcondition of the function is not verified in any case for this example

**Comment by bobismijnnaam** [comment]
Related: https://github.com/viperproject/silicon/issues/369

**Comment by pieter-bos** [comment]
(1): I can no longer reproduce this kind of behaviour, I think due to some combination of functions being verified soundly, and the precondition being boxed in a separate function term guarding the postcondition.
(2): the postcondition of this function is no longer verified incorrectly.

Feel free to re-open this issue if you can alter the verification of a method due to the presence of a function that is not used anywhere in the method.
