### ISSUE TITLE
'-' operator not working for bags in Java

### ISSUE THREAD

**Issue by JLedelay** [utwente-fmt/vercors#772]
When using the following file as input, I get an error at line 8 (the second assert), stating that '-' is expecting two numerals, not two bag<int>s.

According to [the wiki](https://github.com/utwente-fmt/vercors/wiki/Axiomatic-Data-Types#constructing-bags-from-existing-bags), this should be supported but seems not to work with Java.

```
class Test {
  //@ resource mylockset(bag<int> xs);
  
  //@ given bag<int> x;
  //@ requires mylockset(x);
  void foo() {
   //@ assert mylockset(x);
   //@ assert mylockset(x - bag<int>{0});
  }
}
```

```
[INFO] Starting verification
======================================
At practice\Test.java:8:25:
--------------------------------------
    6    void foo() {
    7     //@ assert mylockset(x);
                              [---------------
    8     //@ assert mylockset(x - bag<int>{0});
                               ---------------]
    9    }
   10  }
--------------------------------------```

This happens in alpha.8 and apparently also on the cutting edge ast.

**Comment by niomaster** [comment]
I fixed some instances where parse nodes were erroneously translated to `X` instead of `AmbiguousX`, which is the facility that overloads operators such as `-`, `+` and so on to support bags, sequences, etc.
