### ISSUE TITLE
Using fields in precondition of constructor causes error 

### ISSUE THREAD

**Issue by bobismijnnaam** [utwente-fmt/vercors#778]
The following program:

```java
class C {
   int x;

   //@ requires x == 0;
   C() {

   }
}
```

Causes the following error:

```
[INFO] Starting verification
A rewrite caused the AST to no longer typecheck:
======================================
At /home/bobe/Downloads/result_repro.java:5:4:
--------------------------------------
    3  
    4     //@ requires x == 0;
         [-------
    5     C() {
    6  
    7     }
       ----]
    8  }
    9
--------------------------------------
\result may only occur in the postcondition.
======================================
```

I think this should actually be fine? Possibly the contracts needs to be checked after field assignments, though, but that's a different problem... This is also related to #294, fixing that would indirectly fix this issue also.

**Comment by niomaster** [comment]
Yeah, I'm aware that this error is not ideal, but I don't really see when you would want to mention the objects' fields in the requirements? I'm not really sure it's even encodable, but happy to be proven wrong of course :)

**Comment by bobismijnnaam** [comment]
The one scenario that I have in mind is, assuming some class D:

```java
class C {
  int x = D.foo();
  
  //@ requires x > 0;
  C() {

  }
}
```

Meaning, when is the precondition checked w.r.t. initialization of the class instance. But that's not only a problem of encoding, it is also a problem of what java semantics is implemented...

**Comment by niomaster** [comment]
The java semantics are complete wrt instance initialization, i.e. field initialization, then [instance initializers](https://docs.oracle.com/javase/specs/jls/se7/html/jls-8.html#jls-8.6), then the constructor. This is all inline, so it's not necessary as a proof step to require `x > 0`.
