### ISSUE TITLE
Unclear error message for Future field initialisation

### ISSUE THREAD

**Issue by ArmborstL** [utwente-fmt/vercors#787]
Running https://github.com/utwente-fmt/vercors/blob/51cd18be3d0360a1fa0066539f2da6c07abe3b57/examples/concepts/futures/NoSendAfterRead.java in VerCors 2.0 gives
`[ERROR] It is not possible to initialize an array of which the elements are of type 'Future' to default values.` even though there is no array.
@niomaster conjectured that the procedure assigning default values, which used to be only for arrays, is now also used for fields, thus this error is caused by the `Future` field on L31, for which VerCors cannot deduce a default value. In that case, we should think of a default value for models (maybe `new Future()`?).
In any case, the error message should be adapted to refer to e.g. fields rather than arrays specifically.

**Comment by niomaster** [comment]
The error message is now clearer, and process models are not planned for now.
