### ISSUE TITLE
Triggers in nested forall statements lost in transformation

### ISSUE THREAD

**Issue by JLedelay** [utwente-fmt/vercors#803]
The input below gives a warning regarding lines 11-12 (the injectivity loop invariants):
```java
class C {
  Object[] arr;

  C() {
    int T = 5;
    arr = new Object[T];
    /*@
      loop_invariant Value(arr) ** \array(arr, T);
      loop_invariant Perm(arr[*], write);
      loop_invariant 0 <= i && i <= T;
      loop_invariant (\forall int j = 0 .. i; (\forall int k = 0 .. i; j != k ==> {:<:arr[j]:} != {:arr[k]:}));
      loop_invariant (\forall int j, int k; 0 <= j && j < i && 0 <= k && k < i; j != k ==> {:arr[j]:} != {:arr[k]:});
    @*/
    for (int i = 0; i < T; i++) {
      arr[i] = new Object();
      //@ assume (\forall int j = 0 .. i; arr[j] != arr[i]);
    }  
  }
}
```
The warning:
```
[WARN] The binder '(\forall int j; true; (j\memberof{0 .. i}) ==> (\forall int k; true; (k\memberof{0 .. i}) && j != k ==> {: this.arr[j] :} != {: this.arr[k] :}))' contains no triggers
[WARN] The binder '(\forall int j; true; (\forall int k; true; (j\memberof{0 .. i}) && 0 <= k && k < i && j != k ==> {: this.arr[j] :} != {: this.arr[k] :}))' contains no triggers
```
In transformation, the information that the trigger `arr[j]` applies to the outer `forall` is lost. For the second one, an outer `forall` is added, invalidating the inner triggers (since the outer `forall` has no triggers)

**Comment by JLedelay** [comment]
Aside from this, there's an issue with propagating the information that 'new Object();' generates a new memory location - without the line ```  //@ assume (\forall int j = 0 .. i; arr[j] != arr[i]);```, verification fails. Should a separate issue be made for this?

**Comment by niomaster** [comment]
Ah, that's a classic :)

see also https://github.com/utwente-fmt/vercors/issues/294

**Comment by niomaster** [comment]
In general vercors is not careful about maintaining the nesting of quantifiers: it just collapses and uncollapses them at will (since logically `forall i, j :: x` is equivalent to `forall i :: forall j :: x`). We need to consider all the places where we do that.
