### ISSUE TITLE
Perm (a[i],write) even-odd

### ISSUE THREAD

**Issue by sjcjoosten** [utwente-fmt/vercors#82]
Marieke put this issue on the whiteboard, but I don't know what it means. 
This ticket is made because I don't want to loose track of it.
(should be assigned to Mohsen)

**Comment by Safari1991** [comment]
The issue is that for example this can be verified by the tool:
ensures (\forall int i; i >= 0 && i < array.length; i == 0 ? array[i] == 0 : array[i] == i);

but if we rewrite it in this way, it fails:
ensures array[0] == 0;
ensures (\forall int i; i > 0 && i < array.length; array[i] == i);

**Comment by Safari1991** [comment]
This is not actually a bug in the tool. I have run the equivalent Silver program in Viper and it also gives an error. The error is that the index of array in 'ensures array[0] == 0' can exceed the array length. Therefore we need to mention explicitly 'requires array.length > 0'. Therefore, those two are not the same statements.
