### ISSUE TITLE
Carbon does not optimize effectively heap-independent functions

### ISSUE THREAD

**Issue by niomaster** [utwente-fmt/vercors#834]
This leads to an incompleteness with regards to array bounds checking + triggers:

```
context a != null && a.length > 0;
context Perm(a[*], write);
void clear_head(int[] a)
{ a[0] = 0; }
```

This does not verify in carbon due to insufficient permission in the postcondition. This is due to the way we encode array access:

```
adt array {
  pure ref array_loc(array a, int i);
  pure int alen(array a);

  pure array loc_inv_1(ref loc);
  pure int loc_inv_2(ref loc);

  axiom
    (\forall array a, int i; true;
      loc_inv_1({:array_loc(a, i):}) == a && loc_inv_2(array_loc(a, i)) == i);

  axiom (\forall array a; true; {:alen(a):} >= 0);
}

requires 0 <= i && i < `array`.alen(a);
ensures `array`.loc_inv_1(\result) == a;
ensures `array`.loc_inv_2(\result) == i;
pure ref aloc(array a, int i) = `array`.array_loc(a, i);
```

Here `aloc` is treated (by both silicon and carbon) as a potentially heap-dependent function, and gains a "heap argument". In silicon, this argument becomes a constant, but not in carbon, and so we can't establish that `aloc(a, i) == old(aloc(a, i))`. Consequently, the permission from the precondition in the example above is not triggered, since `aloc(h, a, i)` is not definitely triggered by `aloc(h', a, i)` unless carbon establishes `h == h'` (which is false).

**Comment by Naum-Tomov** [comment]
The way this method is encoded causes the issue:
```
method clear_head(tid: Int, a: option[array]) returns (res: void)
  requires a != (None(): option[array])
  requires 0 < alen(opt_get1(a))
  requires (forall i: Int :: { array_loc((option_get(a): array), i).int } 0 < alen(opt_get1(a)) && (0 <= i && i < alen(opt_get1(a))) ==> acc(aloc(opt_get1(a), i).int, write))
  ensures a != (None(): option[array])
  ensures 0 < alen(opt_get1(a))
  ensures (forall i: Int :: { array_loc((option_get(a): array), i).int } 0 < alen(opt_get1(a)) && (0 <= i && i < alen(opt_get1(a))) ==> acc(aloc(opt_get1(a), i).int, write))
```
The triggers need to be replaced by `array_loc((option_get(a): array), i)`, to solve the issue, but this may make verifications a lot slower.
