### ISSUE TITLE
Yields cannot access local ghost variable

### ISSUE THREAD

**Issue by ArmborstL** [utwente-fmt/vercors#837]
The following (Java) code causes an error in VerCors:
```java
class GhostOut {
    //@ yields int x;
    void meth();
    
    void caller() {
        //@ ghost int y;
        meth() /*@yields {y=x}*/;
    }
}
```
For the `yields` assignment in `caller`, it says _"Could not find local named y."_ 
I expect that `y` should be accessible at this point, given that this is the text-book use case of ghost variables (cf. https://github.com/utwente-fmt/vercors/wiki/Specification-Syntax#ghost-parameters-and-results).

**Comment by axel-b** [comment]
Hmm... I looked up the text-book use case, and there the opening  /*@  is closed by  @*/  whereas your example only has   */  
I have no idea whether this is in anyway important or relevant...
(if this difference is importance, I guess the vercors tool could have been more helpful in its error messages... )
