### ISSUE TITLE
Veymont examples all lack permissions to verify. Adding the permissions in the necessary places is non-trivial

### ISSUE THREAD

**Issue by Naum-Tomov** [utwente-fmt/vercors#840]

**Comment by bobismijnnaam** [comment]
Just wan to mention that VeyMont also does permission generation; not sure if that's relevant for the examples you have in mind, though.

**Comment by pieter-bos** [comment]
@bobismijnnaam is it?

**Comment by bobismijnnaam** [comment]
I plan on having examples that either verify in combination with `--veymont-generate-permissions`, or that have annotations such that the flag is not needed. I'm implementing this for the artefact to be submitted at FM next month.
