### ISSUE TITLE
Program with quantifiers Verifies, but should not.

### ISSUE THREAD

**Issue by sakehl** [utwente-fmt/vercors#855]
The following PVL program verifies, but it should not. I try to prove that the array `g` contains even numbers, but actually, it will produce odd numbers for the first 6 elements. 

```java
context_everywhere inp != null;
context_everywhere inp.length == 6;
context_everywhere g != null;
context_everywhere g.length == 12;

context (\forall* int x; 0<=x && x<6; Perm(inp[x], read));
context (\forall* int y, int x; 0<=x && x<6 && 0<=y && y<2; Perm(g[6*y+x], write));
// This should be needed to verify
requires (\forall int x; 0 <= x && x < 6; inp[x] % 2 == 0);
requires (\forall int x, int y; 0 <= x && x < 6 && 0<=y && y<2; g[6*y+x] == inp[x] + inp[y]);

ensures (\forall int i; 0<=i && i<12; g[i] % 2 == 0);
void main(int[6] inp, int[12] g){
  loop_invariant x >= 0 && x<=6;
  loop_invariant (\forall* int i; 0<=i && i<6; Perm(g[i], write));
  loop_invariant (\forall* int i; 0<=i && i<6; Perm(g[6+i], 1\2));

  loop_invariant (\forall* int x; 0<=x && x<6; Perm(inp[x], read));
  loop_invariant (\forall int x; 0 <= x && x < 6; inp[x] % 2 == 0);
  loop_invariant (\forall int i; x<=i && i<6; g[i] == inp[i] + inp[0]);
  // loop_invariant (\forall int i; x<=i && i<6; g[i] % 2 == 0);

  loop_invariant (\forall int x; 0<=x && x<6; g[6+x] == inp[x] + inp[1]);
  loop_invariant (\forall int i; 0<=i && i<x; g[i] % 2 == 0);
  // loop_invariant (\forall int i; 0<=i && i<6; g[i] % 2 == 0);
  for (int x=0; x<6; x++){
    // This verifies
    // g[x] = g[x] + g[6+x] + 2;
    // g[x] = g[6+x] + 2;
    // The line below also verifies
    g[x] = g[x] + g[6+x] + 1;
  }
}
```
The following file contains the silicon code that is produced (with --backend-file).
[halide_schedule_3_min.txt](https://github.com/utwente-fmt/vercors/files/9901083/halide_schedule_3_min.txt)

If I change line 182 of the silicon file and change the triggers from:

```java
{ aloc(opt_get2(g), i).int }
```

towards
```java
{ aloc(opt_get2(g), i).int, aloc(opt_get2(inp), i).int }
```
It does seem to verify in the correct manner, as in, with the incorrect line I get an error, with the correct line it verifies. 

So it seems it has trouble with the line:
```java
loop_invariant (\forall int i; x<=i && i<6; g[i] == inp[i] + inp[0]);
```

But wait, there is more...
So this example is stripped down example from this PVL file. 
[halide_schedule_3.txt](https://github.com/utwente-fmt/vercors/files/9900949/halide_schedule_3.txt)

This has the nice feature that if try to verify it (It should fail, cause it has a similar error) then for approximately 3 runs, 2 times it verifies (it shouldn't) and 1 times it gives a verification error (but the error is unrelated to the actual cause that it should not verify)

I would just really like to get failed verification in these cases since it seems the tool is not sound now. (Right? or am I missing something)

I am on commit a635839b24b18cc21d0e26978dbf3699efb988c2 btw.

**Comment by niomaster** [comment]
Related: <https://github.com/viperproject/silicon/issues/652>
