### ISSUE TITLE
Tutorial

### ISSUE THREAD

**Issue by sjcjoosten** [utwente-fmt/vercors#88]
VerCors needs a good tutorial

**Comment by sjcjoosten** [comment]
From issue #193 here's Wytse's pvl snippet that shows how to use permissions in a resource:

```java
class MyClass {
  resource hasPerm(MyClass c) = c != null ** Perm(c.P, 1/2);

  int[] P;
	
  MyClass() {
  }
  
  requires hasPerm(this);
  void foo() {
    unfold hasPerm(this);
    assert Perm(P, 1/2);
  }
}
```

We might in the same place explain why this can't work:
```java
resource hasPerm(int[] arr) = Perm(arr, 1/2);
```
(arr is on the stack since it is an argument, so we implicitly have permission)

**Comment by Sophietje** [comment]
So we decided to (finally) start working on putting a tutorial together. We have identified the following things that need to be discussed (the names indicate who is responsible for writing which part):

- [ ] Introduction (pre-/postconditions/asserts/loop invariants) to verification
- [ ] Basic building blocks (for, while, classes, methods, etc.)
- [ ] Syntax (Make the separation between annotations/pvl/java/c clear and what is supported for java and c)
- [ ] OpenCL/Cuda/GPGPU stuff (**Mohsen**)
- [ ] Permissions (including separation logic) (**Sophie**)
- [ ] Resources and predicates (**Bob**)
- [ ] Axiomatic Data Types (**Ömer**)
- [ ] Arrays / Pointers (**Pieter**)
- [ ] Parallel blocks (and barriers) (**Mohsen**)
- [ ] Atomics and locks (+ invariants) (**Raúl**)
- [ ] Models (Histories/Futures) (**Raúl**)
- [ ] Inheritance (**Bob**)
- [ ] Exceptions (**Bob**)

**Comment by ArmborstL** [comment]
Distribution of language constructs across the chapters: [SpecParser.pdf](https://github.com/utwente-fmt/vercors/files/4725292/SpecParser.pdf)

**Comment by niomaster** [comment]
We have declared the tutorial finished for now! :D
