### ISSUE TITLE
Syntax of PVL

### ISSUE THREAD

**Issue by sjcjoosten** [utwente-fmt/vercors#91]
The syntax of PVL might be extended with a for loop and and postfix ++. This issue is there to discuss what should be added, and track its progress.

**Comment by wytseoortwijn** [comment]
There are some notes on the `++` infix operator, which you can find click [here](https://github.com/utwente-fmt/vercors/wiki/Prototypal-Verification-Language).

**Comment by Sophietje** [comment]
For-loops have been added in PR #184 but I believe that i++ is not yet supported.

**Comment by Vescatur** [comment]
Is already supported.
