### ISSUE TITLE
`.git` folder required for compilation

### ISSUE THREAD

**Issue by bobismijnnaam** [utwente-fmt/vercors#919]
Compilation fails if there's not a functional `.git` folder present. While not a blocking issue, it'd probably be better to make compilation succeed even if there is no `.git` folder (or if there's no `git` available, for that matter).

**Comment by niomaster** [comment]
iirc the caching component allows for there to be no git information, in which case the cache is essentially not used. It's important though that different compilations do not overlap in the cache for now.

**Comment by bobismijnnaam** [comment]
Ah, I forgot that the git info is used for more than just `--version`. Perhaps in that case we can put a UUID, or a very precise timestamp, in the binary? That way you can still distinguish individual compilation runs.

**Comment by niomaster** [comment]
I think that's fine (we would need to weigh always invalidating the build vs having caching in a non-standard compilation situation).
