### ISSUE TITLE
Second par block is not executed

### ISSUE THREAD

**Issue by bobismijnnaam** [utwente-fmt/vercors#938]
If I am not missing something, in the following program the assert fails, where I think it shouldn't:

```
class C { int x; }

void m() {
  C c = new C();

  /* Turn this one  off to make the assert pass */ par (int i = 0 .. 0) { } and

  par (int i = 0 .. 1)
  context Perm(c.x, write);
  ensures c.x == 3;
  {
    c.x = 3;
  }

  assert c.x == 3;
}
```

When the first par section is removed it does verify. Is the encoding never executing somehow? I did see in the viper file that the second par block had an "inhale false" at the end, implying that the control flow never goes beyond the second par block somehow...?

**Comment by bobismijnnaam** [comment]
Thanks! Maybe we can document this caveat on the wiki or kick out the old syntax; the second option has my preference :)

**Comment by niomaster** [comment]
for completeness, the new syntax I propose is as such:

```
parRegion
 : 'parallel' '{' parRegion* '}' # pvlParallel
 | 'sequential' '{' parRegion* '}' # pvlSequential
 | 'block' identifier? parBlockIter? contract statement # pvlParBlock
 ;
```
