### ISSUE TITLE
Uninitialized final variables are (wrongly) given value 0

### ISSUE THREAD

**Issue by bobismijnnaam** [utwente-fmt/vercors#942]
The following program verifies, where I think the assert should fail:

```java
class C {
    //@ ghost final int T;
    void m() {
        //@ assert T == 0;
    }
}
```

I think we need to better encode that the default value of a final field should not be used for the constantifying optimization...

**Comment by niomaster** [comment]
I'm guessing this doesn't compile, since the field is not initialized despite being final? In that case I don't think it's all that important.

**Comment by bobismijnnaam** [comment]
Ah, yes, I agree. An argument can be made that ghost declarations should be more restrictive, possibly (e.g. disallowing final on ghost fields)? As the java compiler doesn't check ghost code? Though I don't think that's much easier to implement unfortunately.

**Comment by bobismijnnaam** [comment]
I think we cannot escape from implementing a small part of the JLS regarding this, as the following also wrongly verifies:

```public class Y {
	public final boolean b;

    //@ requires x;
	//@ ensures b == x;
	public Y(boolean x) {
		b = x;
        //@ assert false;
	}
}```

**Comment by niomaster** [comment]
Yes, you are right.
